//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Billing
{
    public partial class BillingTypeDetail
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string BillingOCC
        {
            get;
            set;
        }
    
        public string BillingTypeCode
        {
            get;
            set;
        }
    
        public string BillingTypeNameEN
        {
            get;
            set;
        }
    
        public string BillingTypeNameLC
        {
            get;
            set;
        }
    
        public string BillingTypeNameJP
        {
            get;
            set;
        }
    
        public string InvoiceDescriptionEN
        {
            get;
            set;
        }
    
        public string InvoiceDescriptionLC
        {
            get;
            set;
        }
    
        public Nullable<bool> IssueInvoiceFlag
        {
            get;
            set;
        }
    
        public string BillingTypeGroup
        {
            get;
            set;
        }

        #endregion

    }
}
