//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Billing
{
    public partial class doBLS050GetBillingBasic
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string BillingOCC
        {
            get;
            set;
        }
    
        public string BillingTargetCode
        {
            get;
            set;
        }
    
        public string PreviousBillingTargetCode
        {
            get;
            set;
        }
    
        public string DebtTracingOfficeCode
        {
            get;
            set;
        }
    
        public Nullable<bool> ResultBasedMaintenanceFlag
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> StartOperationDate
        {
            get;
            set;
        }
    
        public Nullable<decimal> MonthlyBillingAmount
        {
            get;
            set;
        }
    
        public string PaymentMethod
        {
            get;
            set;
        }
    
        public string PaymentMethodNameEN
        {
            get;
            set;
        }
    
        public string PaymentMethodNameLC
        {
            get;
            set;
        }
    
        public string PaymentMethodNameJP
        {
            get;
            set;
        }
    
        public Nullable<int> BillingCycle
        {
            get;
            set;
        }
    
        public Nullable<int> CreditTerm
        {
            get;
            set;
        }
    
        public string CalDailyFeeStatus
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> LastBillingDate
        {
            get;
            set;
        }
    
        public Nullable<bool> CarefulFlag
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> AdjustEndDate
        {
            get;
            set;
        }
    
        public string SortingType
        {
            get;
            set;
        }
    
        public Nullable<bool> StopBillingFlag
        {
            get;
            set;
        }
    
        public Nullable<decimal> MonthlyFeeBeforeStop
        {
            get;
            set;
        }
    
        public Nullable<decimal> BalanceDeposit
        {
            get;
            set;
        }
    
        public Nullable<bool> VATUnchargedFlag
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> ChangeDate
        {
            get;
            set;
        }
    
        public string ApproveNo
        {
            get;
            set;
        }
    
        public string DocReceiving
        {
            get;
            set;
        }
    
        public string AdjustType
        {
            get;
            set;
        }
    
        public Nullable<decimal> AdjustBillingPeriodAmount
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> AdjustBillingPeriodStartDate
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> AdjustBillingPeriodEndDate
        {
            get;
            set;
        }
    
        public Nullable<decimal> BalanceDepositUsd
        {
            get;
            set;
        }
    
        public string BalanceDepositCurrencyType
        {
            get;
            set;
        }
    
        public Nullable<decimal> AdjustBillingPeriodAmountUsd
        {
            get;
            set;
        }
    
        public string AdjustBillingPeriodAmountCurrencyType
        {
            get;
            set;
        }

        #endregion

    }
}
