//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Billing
{
    public partial class doGetBankAutoTransferDateForGen
    {
        #region Primitive Properties
    
        public string BankCode
        {
            get;
            set;
        }
    
        public string AutoTransferDate
        {
            get;
            set;
        }
    
        public System.DateTime GenerateDate
        {
            get;
            set;
        }

        #endregion

    }
}
