//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Billing
{
    public partial class dtRptTaxInvoice
    {
        #region Primitive Properties
    
        public string TaxInvoiceNo
        {
            get;
            set;
        }
    
        public string TaxInvoiceDate
        {
            get;
            set;
        }
    
        public string TaxInvoiceDate_Buddhist
        {
            get;
            set;
        }
    
        public string InvoiceNo
        {
            get;
            set;
        }
    
        public int InvoiceOCC
        {
            get;
            set;
        }
    
        public string IssueInvDate
        {
            get;
            set;
        }
    
        public string IssueInvDate_Buddhist
        {
            get;
            set;
        }
    
        public string ShowDueDate
        {
            get;
            set;
        }
    
        public string DueDate7DescEN
        {
            get;
            set;
        }
    
        public string DueDate7DescJP
        {
            get;
            set;
        }
    
        public string DueDate7DescLC
        {
            get;
            set;
        }
    
        public string DueDate30DescEN
        {
            get;
            set;
        }
    
        public string DueDate30DescJP
        {
            get;
            set;
        }
    
        public string DueDate30DescLC
        {
            get;
            set;
        }
    
        public string ShowAccType
        {
            get;
            set;
        }
    
        public string AccountNo
        {
            get;
            set;
        }
    
        public string BankCode
        {
            get;
            set;
        }
    
        public string BankBranchCode
        {
            get;
            set;
        }
    
        public string BankNameEN
        {
            get;
            set;
        }
    
        public string BankNameLC
        {
            get;
            set;
        }
    
        public string BankBranchNameEN
        {
            get;
            set;
        }
    
        public string BankBranchNameLC
        {
            get;
            set;
        }
    
        public string BillingClientNameEN
        {
            get;
            set;
        }
    
        public string BillingClientNameLC
        {
            get;
            set;
        }
    
        public string SuppleInvAddress
        {
            get;
            set;
        }
    
        public string BillingClientAddressEN
        {
            get;
            set;
        }
    
        public string BillingClientAddressLC
        {
            get;
            set;
        }
    
        public string DocLanguage
        {
            get;
            set;
        }
    
        public string ShowIssueDate
        {
            get;
            set;
        }
    
        public decimal InvoiceAmount
        {
            get;
            set;
        }
    
        public decimal VatRate
        {
            get;
            set;
        }
    
        public decimal VatAmount
        {
            get;
            set;
        }
    
        public decimal WHTRate
        {
            get;
            set;
        }
    
        public decimal WHTAmount
        {
            get;
            set;
        }
    
        public string ContactPersonName
        {
            get;
            set;
        }
    
        public string PhoneNo
        {
            get;
            set;
        }
    
        public string PaymentMethod
        {
            get;
            set;
        }
    
        public bool PayByChequeFlag
        {
            get;
            set;
        }
    
        public string BillingOfficeCode
        {
            get;
            set;
        }
    
        public bool ShowInvWHTFlag
        {
            get;
            set;
        }
    
        public string SeparateInvType
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string BillingOCC
        {
            get;
            set;
        }
    
        public int BillingDetailNo
        {
            get;
            set;
        }
    
        public string BillingTypeCode
        {
            get;
            set;
        }
    
        public decimal BillingAmount
        {
            get;
            set;
        }
    
        public string BillingStartDate
        {
            get;
            set;
        }
    
        public string BillingStartDate_Buddhist
        {
            get;
            set;
        }
    
        public string BillingEndDate
        {
            get;
            set;
        }
    
        public string BillingEndDate_Buddhist
        {
            get;
            set;
        }
    
        public bool FirstFeeFlag
        {
            get;
            set;
        }
    
        public string InvoiceDescriptionEN
        {
            get;
            set;
        }
    
        public string InvoiceDescriptionLC
        {
            get;
            set;
        }
    
        public string SortingType
        {
            get;
            set;
        }
    
        public string BillingTypeGroup
        {
            get;
            set;
        }
    
        public string SiteCode
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }
    
        public int Page
        {
            get;
            set;
        }
    
        public string BillingTargetCode
        {
            get;
            set;
        }
    
        public string SignatureType
        {
            get;
            set;
        }
    
        public string EmpName
        {
            get;
            set;
        }
    
        public string EmpPosition
        {
            get;
            set;
        }
    
        public string ImageFileName
        {
            get;
            set;
        }
    
        public string RealBillingClientNameEN
        {
            get;
            set;
        }
    
        public string RealBillingClientNameLC
        {
            get;
            set;
        }
    
        public string RealBillingClientAddressEN
        {
            get;
            set;
        }
    
        public string RealBillingClientAddressLC
        {
            get;
            set;
        }
    
        public string BillingOffceNameLC
        {
            get;
            set;
        }
    
        public int CreditTerm
        {
            get;
            set;
        }
    
        public string IDNo
        {
            get;
            set;
        }
    
        public string BranchNameEN
        {
            get;
            set;
        }
    
        public string BranchNameLC
        {
            get;
            set;
        }
    
        public string BranchNo
        {
            get;
            set;
        }
    
        public string DueDate14DescEN
        {
            get;
            set;
        }
    
        public string DueDate14DescJP
        {
            get;
            set;
        }
    
        public string DueDate14DescLC
        {
            get;
            set;
        }
    
        public string DueDateNoneDescEN
        {
            get;
            set;
        }
    
        public string DueDateNoneDescJP
        {
            get;
            set;
        }
    
        public string DueDateNoneDescLC
        {
            get;
            set;
        }

        #endregion

    }
}
