//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MAS050 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MAS050() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MAS050", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group code.
        /// </summary>
        internal static string headerGroupCode {
            get {
                return ResourceManager.GetString("headerGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name&lt;br/&gt;(English).
        /// </summary>
        internal static string headerGroupNameEN {
            get {
                return ResourceManager.GetString("headerGroupNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name&lt;br/&gt;(Local).
        /// </summary>
        internal static string headerGroupNameLC {
            get {
                return ResourceManager.GetString("headerGroupNameLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none&quot;&gt;Remove&lt;/div&gt;.
        /// </summary>
        internal static string headerRemove {
            get {
                return ResourceManager.GetString("headerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building information.
        /// </summary>
        internal static string lblAddressInformation {
            get {
                return ResourceManager.GetString("lblAddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string lblAdress {
            get {
                return ResourceManager.GetString("lblAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building (English).
        /// </summary>
        internal static string lblAdressEN {
            get {
                return ResourceManager.GetString("lblAdressEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building (Local).
        /// </summary>
        internal static string lblAdressLC {
            get {
                return ResourceManager.GetString("lblAdressLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota/Kabupaten.
        /// </summary>
        internal static string lblAmper_Ked {
            get {
                return ResourceManager.GetString("lblAmper_Ked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota/Kabupaten (English).
        /// </summary>
        internal static string lblAmper_KedEN {
            get {
                return ResourceManager.GetString("lblAmper_KedEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota/Kabupaten (Local).
        /// </summary>
        internal static string lblAmper_KedLC {
            get {
                return ResourceManager.GetString("lblAmper_KedLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business category.
        /// </summary>
        internal static string lblBusinessType {
            get {
                return ResourceManager.GetString("lblBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company type.
        /// </summary>
        internal static string lblCompanyType {
            get {
                return ResourceManager.GetString("lblCompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code.
        /// </summary>
        internal static string lblCustomerCode {
            get {
                return ResourceManager.GetString("lblCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer PIC.
        /// </summary>
        internal static string lblCustomerContact {
            get {
                return ResourceManager.GetString("lblCustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer group code.
        /// </summary>
        internal static string lblCustomerGroupCode {
            get {
                return ResourceManager.GetString("lblCustomerGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information.
        /// </summary>
        internal static string lblCustomerInfornmation {
            get {
                return ResourceManager.GetString("lblCustomerInfornmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer status.
        /// </summary>
        internal static string lblCustomerStatus {
            get {
                return ResourceManager.GetString("lblCustomerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer type.
        /// </summary>
        internal static string lblCustomerType {
            get {
                return ResourceManager.GetString("lblCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy NPWP.
        /// </summary>
        internal static string lblDummyIDno_TaxIDno {
            get {
                return ResourceManager.GetString("lblDummyIDno_TaxIDno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lblEn {
            get {
                return ResourceManager.GetString("lblEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax no..
        /// </summary>
        internal static string lblFaxNo {
            get {
                return ResourceManager.GetString("lblFaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial market type.
        /// </summary>
        internal static string lblFinancialMarketType {
            get {
                return ResourceManager.GetString("lblFinancialMarketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register customer information (CP-00).
        /// </summary>
        internal static string lblHeader {
            get {
                return ResourceManager.GetString("lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS050.
        /// </summary>
        internal static string lblHeaderCode {
            get {
                return ResourceManager.GetString("lblHeaderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPWP.
        /// </summary>
        internal static string lblIDno_TaxIDno {
            get {
                return ResourceManager.GetString("lblIDno_TaxIDno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinsi.
        /// </summary>
        internal static string lblJangwat {
            get {
                return ResourceManager.GetString("lblJangwat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinsi (English).
        /// </summary>
        internal static string lblJangwatEN {
            get {
                return ResourceManager.GetString("lblJangwatEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinsi (Local).
        /// </summary>
        internal static string lblJangwatLC {
            get {
                return ResourceManager.GetString("lblJangwatLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string lblLc {
            get {
                return ResourceManager.GetString("lblLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        internal static string lblName_English {
            get {
                return ResourceManager.GetString("lblName_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Local).
        /// </summary>
        internal static string lblName_Local {
            get {
                return ResourceManager.GetString("lblName_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President director’s name.
        /// </summary>
        internal static string lblRepresentativePersonName {
            get {
                return ResourceManager.GetString("lblRepresentativePersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desa/Kel.
        /// </summary>
        internal static string lblRoad {
            get {
                return ResourceManager.GetString("lblRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desa/Kel (English).
        /// </summary>
        internal static string lblRoadEN {
            get {
                return ResourceManager.GetString("lblRoadEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desa/Kel (Local).
        /// </summary>
        internal static string lblRoadLC {
            get {
                return ResourceManager.GetString("lblRoadLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOM PIC.
        /// </summary>
        internal static string lblSECOMContact {
            get {
                return ResourceManager.GetString("lblSECOMContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JL.
        /// </summary>
        internal static string lblSoi {
            get {
                return ResourceManager.GetString("lblSoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string lblStar {
            get {
                return ResourceManager.GetString("lblStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kecamatan.
        /// </summary>
        internal static string lblTambol_Kwaeng {
            get {
                return ResourceManager.GetString("lblTambol_Kwaeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kecamatan (English).
        /// </summary>
        internal static string lblTambol_KwaengEN {
            get {
                return ResourceManager.GetString("lblTambol_KwaengEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kecamatan (Local).
        /// </summary>
        internal static string lblTambol_KwaengLC {
            get {
                return ResourceManager.GetString("lblTambol_KwaengLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone no..
        /// </summary>
        internal static string lblTelephoneNo {
            get {
                return ResourceManager.GetString("lblTelephoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string lblURL {
            get {
                return ResourceManager.GetString("lblURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        internal static string lblZipCode {
            get {
                return ResourceManager.GetString("lblZipCode", resourceCulture);
            }
        }
    }
}
