//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MAS120 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MAS120() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MAS120", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btnNew {
            get {
                return ResourceManager.GetString("btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area code.
        /// </summary>
        internal static string headerAreaCode {
            get {
                return ResourceManager.GetString("headerAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Edit&lt;/div&gt;.
        /// </summary>
        internal static string headerEdit {
            get {
                return ResourceManager.GetString("headerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string headerInstrumentName {
            get {
                return ResourceManager.GetString("headerInstrumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack name.
        /// </summary>
        internal static string headerShelfName {
            get {
                return ResourceManager.GetString("headerShelfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no..
        /// </summary>
        internal static string headerShelfNo {
            get {
                return ResourceManager.GetString("headerShelfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack type.
        /// </summary>
        internal static string headerShelfTypeCode {
            get {
                return ResourceManager.GetString("headerShelfTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area code.
        /// </summary>
        internal static string lblAreaCode {
            get {
                return ResourceManager.GetString("lblAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rack.
        /// </summary>
        internal static string lblDeleteShelf {
            get {
                return ResourceManager.GetString("lblDeleteShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string lblInstrument {
            get {
                return ResourceManager.GetString("lblInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result list.
        /// </summary>
        internal static string lblResultList {
            get {
                return ResourceManager.GetString("lblResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search rack.
        /// </summary>
        internal static string lblSearchShelf {
            get {
                return ResourceManager.GetString("lblSearchShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack information.
        /// </summary>
        internal static string lblShelfInformation {
            get {
                return ResourceManager.GetString("lblShelfInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack name.
        /// </summary>
        internal static string lblShelfName {
            get {
                return ResourceManager.GetString("lblShelfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no..
        /// </summary>
        internal static string lblShelfNo {
            get {
                return ResourceManager.GetString("lblShelfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack type.
        /// </summary>
        internal static string lblShelfType {
            get {
                return ResourceManager.GetString("lblShelfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
    }
}
