//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICS080 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICS080() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ICS080", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnEncash {
            get {
                return ResourceManager.GetString("btnEncash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First payment amount.
        /// </summary>
        internal static string gridHeaderFirstPaymentAmount {
            get {
                return ResourceManager.GetString("gridHeaderFirstPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice no..
        /// </summary>
        internal static string gridHeaderInvoice {
            get {
                return ResourceManager.GetString("gridHeaderInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;No.&lt;br /&gt;(1) Invoice&lt;br /&gt;(2) Receipt&lt;/div&gt;.
        /// </summary>
        internal static string gridHeaderInvoiceReceipt {
            get {
                return ResourceManager.GetString("gridHeaderInvoiceReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer name or custom description.
        /// </summary>
        internal static string gridHeaderMaBillingClientName {
            get {
                return ResourceManager.GetString("gridHeaderMaBillingClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer code.
        /// </summary>
        internal static string gridHeaderMaBillingTargetCode {
            get {
                return ResourceManager.GetString("gridHeaderMaBillingTargetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice no..
        /// </summary>
        internal static string gridHeaderMaInvoiceNo {
            get {
                return ResourceManager.GetString("gridHeaderMaInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched payment amount.
        /// </summary>
        internal static string gridHeaderMaMatchedPaymentAmount {
            get {
                return ResourceManager.GetString("gridHeaderMaMatchedPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching payment date.
        /// </summary>
        internal static string gridHeaderMaMatchingPaymentDate {
            get {
                return ResourceManager.GetString("gridHeaderMaMatchingPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial payment.
        /// </summary>
        internal static string gridHeaderMaPartialPayment {
            get {
                return ResourceManager.GetString("gridHeaderMaPartialPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt no..
        /// </summary>
        internal static string gridHeaderMaReceiptNo {
            get {
                return ResourceManager.GetString("gridHeaderMaReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchable balance .
        /// </summary>
        internal static string gridHeaderMatchableBalance {
            get {
                return ResourceManager.GetString("gridHeaderMatchableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching payment date.
        /// </summary>
        internal static string gridHeaderMatchingPaymentDate {
            get {
                return ResourceManager.GetString("gridHeaderMatchingPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string gridHeaderMemo {
            get {
                return ResourceManager.GetString("gridHeaderMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;(1) Payer name&lt;br/&gt;(2) Match-R group name&lt;/div&gt;.
        /// </summary>
        internal static string gridHeaderPayerName {
            get {
                return ResourceManager.GetString("gridHeaderPayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date.
        /// </summary>
        internal static string gridHeaderPaymentDate {
            get {
                return ResourceManager.GetString("gridHeaderPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment transaction no..
        /// </summary>
        internal static string gridHeaderPaymentTransNo {
            get {
                return ResourceManager.GetString("gridHeaderPaymentTransNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        internal static string gridHeaderPaymentType {
            get {
                return ResourceManager.GetString("gridHeaderPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Post dated cheque/&lt;br/&gt;promissory note&lt;br /&gt;(1) No.&lt;br /&gt;(2) Date&lt;/div&gt;.
        /// </summary>
        internal static string gridHeaderPromissoryNoteGrid {
            get {
                return ResourceManager.GetString("gridHeaderPromissoryNoteGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Select&lt;/div&gt;.
        /// </summary>
        internal static string gridHeaderSelect {
            get {
                return ResourceManager.GetString("gridHeaderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending bank.
        /// </summary>
        internal static string gridHeaderSendingBank {
            get {
                return ResourceManager.GetString("gridHeaderSendingBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account no..
        /// </summary>
        internal static string lblAccountNo {
            get {
                return ResourceManager.GetString("lblAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encash remark.
        /// </summary>
        internal static string lblChequeEncashRemark {
            get {
                return ResourceManager.GetString("lblChequeEncashRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return date.
        /// </summary>
        internal static string lblChequeReturnDate {
            get {
                return ResourceManager.GetString("lblChequeReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return reason.
        /// </summary>
        internal static string lblChequeReturnReason {
            get {
                return ResourceManager.GetString("lblChequeReturnReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return remark.
        /// </summary>
        internal static string lblChequeReturnRemark {
            get {
                return ResourceManager.GetString("lblChequeReturnRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search payment transaction information (Delete payment transaction information).
        /// </summary>
        internal static string lblDeleteMaintainName {
            get {
                return ResourceManager.GetString("lblDeleteMaintainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encash.
        /// </summary>
        internal static string lblEncash {
            get {
                return ResourceManager.GetString("lblEncash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encashed.
        /// </summary>
        internal static string lblEncashed {
            get {
                return ResourceManager.GetString("lblEncashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encash information.
        /// </summary>
        internal static string lblEncashInformation {
            get {
                return ResourceManager.GetString("lblEncashInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encash status.
        /// </summary>
        internal static string lblEncashStatus {
            get {
                return ResourceManager.GetString("lblEncashStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First payment amount.
        /// </summary>
        internal static string lblFirstPaymentAmount {
            get {
                return ResourceManager.GetString("lblFirstPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice no..
        /// </summary>
        internal static string lblInvoiceNo {
            get {
                return ResourceManager.GetString("lblInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage payment information.
        /// </summary>
        internal static string lblMaintainName {
            get {
                return ResourceManager.GetString("lblMaintainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchable balance.
        /// </summary>
        internal static string lblMatchableBalance {
            get {
                return ResourceManager.GetString("lblMatchableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string lblMatchableBalanceTo {
            get {
                return ResourceManager.GetString("lblMatchableBalanceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search payment transaction information (Match payment).
        /// </summary>
        internal static string lblMatchMaintainName {
            get {
                return ResourceManager.GetString("lblMatchMaintainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match-R group name.
        /// </summary>
        internal static string lblMatchRGroupName {
            get {
                return ResourceManager.GetString("lblMatchRGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string lblMemo {
            get {
                return ResourceManager.GetString("lblMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My payment.
        /// </summary>
        internal static string lblMyPayment {
            get {
                return ResourceManager.GetString("lblMyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer name.
        /// </summary>
        internal static string lblPayerName {
            get {
                return ResourceManager.GetString("lblPayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date.
        /// </summary>
        internal static string lblPaymentDate {
            get {
                return ResourceManager.GetString("lblPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string lblPaymentDateTo {
            get {
                return ResourceManager.GetString("lblPaymentDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment transaction no..
        /// </summary>
        internal static string lblPaymentTransactionNo {
            get {
                return ResourceManager.GetString("lblPaymentTransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        internal static string lblPaymentType {
            get {
                return ResourceManager.GetString("lblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post dated cheque/&lt;br/&gt;promissory note date.
        /// </summary>
        internal static string lblPromissoryNoteDate {
            get {
                return ResourceManager.GetString("lblPromissoryNoteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post dated cheque/&lt;br/&gt;promissory note no..
        /// </summary>
        internal static string lblPromissoryNoteNo {
            get {
                return ResourceManager.GetString("lblPromissoryNoteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt no..
        /// </summary>
        internal static string lblReceiptNo {
            get {
                return ResourceManager.GetString("lblReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return cheque.
        /// </summary>
        internal static string lblReturnCheque {
            get {
                return ResourceManager.GetString("lblReturnCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOM bank/branch.
        /// </summary>
        internal static string lblSECOMBankBranch {
            get {
                return ResourceManager.GetString("lblSECOMBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View result of payment matching.
        /// </summary>
        internal static string lblSectionViewResultMatching {
            get {
                return ResourceManager.GetString("lblSectionViewResultMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending bank.
        /// </summary>
        internal static string lblSendingBank {
            get {
                return ResourceManager.GetString("lblSendingBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending bank/branch.
        /// </summary>
        internal static string lblSendingBankBranch {
            get {
                return ResourceManager.GetString("lblSendingBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone no..
        /// </summary>
        internal static string lblTelephone {
            get {
                return ResourceManager.GetString("lblTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search payment transaction information (View payment matching result).
        /// </summary>
        internal static string lblViewMaintainName {
            get {
                return ResourceManager.GetString("lblViewMaintainName", resourceCulture);
            }
        }
    }
}
