//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICS084 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICS084() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ICS084", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated paid amount.
        /// </summary>
        internal static string gridHeaderAccumalatedPaid {
            get {
                return ResourceManager.GetString("gridHeaderAccumalatedPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing amount (including tax) .
        /// </summary>
        internal static string gridHeaderBillingAmount {
            get {
                return ResourceManager.GetString("gridHeaderBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice no..
        /// </summary>
        internal static string gridHeaderInvoiceNo {
            get {
                return ResourceManager.GetString("gridHeaderInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date.
        /// </summary>
        internal static string gridHeaderIssueDate {
            get {
                return ResourceManager.GetString("gridHeaderIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match payment amount (including WHT).
        /// </summary>
        internal static string gridHeaderMatchPaymentAmount {
            get {
                return ResourceManager.GetString("gridHeaderMatchPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string gridHeaderSelect {
            get {
                return ResourceManager.GetString("gridHeaderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid amount.
        /// </summary>
        internal static string gridHeaderUnpaidAmount {
            get {
                return ResourceManager.GetString("gridHeaderUnpaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHT amount .
        /// </summary>
        internal static string gridHeaderWhtAmount {
            get {
                return ResourceManager.GetString("gridHeaderWhtAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange gain.
        /// </summary>
        internal static string lbExchangeGain {
            get {
                return ResourceManager.GetString("lbExchangeGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange loss.
        /// </summary>
        internal static string lbExchangeLoss {
            get {
                return ResourceManager.GetString("lbExchangeLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve no..
        /// </summary>
        internal static string lblApproveNo {
            get {
                return ResourceManager.GetString("lblApproveNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance after processing.
        /// </summary>
        internal static string lblBalanceAfterProcessing {
            get {
                return ResourceManager.GetString("lblBalanceAfterProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank fee.
        /// </summary>
        internal static string lblBankFee {
            get {
                return ResourceManager.GetString("lblBankFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer name (English).
        /// </summary>
        internal static string lblBillingClientNameEN {
            get {
                return ResourceManager.GetString("lblBillingClientNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer name (Local).
        /// </summary>
        internal static string lblBillingClientNameLC {
            get {
                return ResourceManager.GetString("lblBillingClientNameLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer code.
        /// </summary>
        internal static string lblBillingTargetCode {
            get {
                return ResourceManager.GetString("lblBillingTargetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First payment amount.
        /// </summary>
        internal static string lblFirstPaymentAmount {
            get {
                return ResourceManager.GetString("lblFirstPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchable balance.
        /// </summary>
        internal static string lblMatchableBalance {
            get {
                return ResourceManager.GetString("lblMatchableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string lblMemo {
            get {
                return ResourceManager.GetString("lblMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other expense.
        /// </summary>
        internal static string lblOtherExpense {
            get {
                return ResourceManager.GetString("lblOtherExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other income.
        /// </summary>
        internal static string lblOtherIncome {
            get {
                return ResourceManager.GetString("lblOtherIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer name.
        /// </summary>
        internal static string lblPayerName {
            get {
                return ResourceManager.GetString("lblPayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date.
        /// </summary>
        internal static string lblPaymentDate {
            get {
                return ResourceManager.GetString("lblPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment transaction no..
        /// </summary>
        internal static string lblPaymentTransNo {
            get {
                return ResourceManager.GetString("lblPaymentTransNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOM bank/branch.
        /// </summary>
        internal static string lblSECOMBankBranch {
            get {
                return ResourceManager.GetString("lblSECOMBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target invoice for payment matching.
        /// </summary>
        internal static string lblSectionTargetInvoice {
            get {
                return ResourceManager.GetString("lblSectionTargetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target payment transaction of payment matching.
        /// </summary>
        internal static string lblSectionTargetPayment {
            get {
                return ResourceManager.GetString("lblSectionTargetPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special process.
        /// </summary>
        internal static string lblSpecialProcess {
            get {
                return ResourceManager.GetString("lblSpecialProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *As for &apos;Other expense&apos; and &apos;Other income&apos;, can register by registering Approve No. In case the process needs to be done by another person who is not authorized person, please declare to authorized person..
        /// </summary>
        internal static string lblSpecialProcessRemark {
            get {
                return ResourceManager.GetString("lblSpecialProcessRemark", resourceCulture);
            }
        }
    }
}
