//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICS130 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICS130() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ICS130", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract no..
        /// </summary>
        internal static string headerContractCode {
            get {
                return ResourceManager.GetString("headerContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;(1) Customer name&lt;br/&gt;(2) Tax ID&lt;/div&gt;.
        /// </summary>
        internal static string headerCustomerNameAndTaxID {
            get {
                return ResourceManager.GetString("headerCustomerNameAndTaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff.
        /// </summary>
        internal static string headerDiff {
            get {
                return ResourceManager.GetString("headerDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;(1) Invoice no&lt;br/&gt;(2) Tax invoice no&lt;/div&gt;.
        /// </summary>
        internal static string headerInvoiceNoAndTaxInvoiceNo {
            get {
                return ResourceManager.GetString("headerInvoiceNoAndTaxInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching amount.
        /// </summary>
        internal static string headerMatchingAmount {
            get {
                return ResourceManager.GetString("headerMatchingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        internal static string headerPayerName {
            get {
                return ResourceManager.GetString("headerPayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date.
        /// </summary>
        internal static string headerPaymentDate {
            get {
                return ResourceManager.GetString("headerPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment transaction no.
        /// </summary>
        internal static string headerPaymentTransNo {
            get {
                return ResourceManager.GetString("headerPaymentTransNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received WHT amount.
        /// </summary>
        internal static string headerReceivedWHTAmount {
            get {
                return ResourceManager.GetString("headerReceivedWHTAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of WHT.
        /// </summary>
        internal static string headerWHTAmount {
            get {
                return ResourceManager.GetString("headerWHTAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHT doc no.
        /// </summary>
        internal static string headerWHTDocNo {
            get {
                return ResourceManager.GetString("headerWHTDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;(1) WHT doc no&lt;br/&gt;(2) WHT doc date&lt;/div&gt;.
        /// </summary>
        internal static string headerWHTDocNoAndWHTDocDate {
            get {
                return ResourceManager.GetString("headerWHTDocNoAndWHTDocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string headerWHTPercent {
            get {
                return ResourceManager.GetString("headerWHTPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string lblAccount {
            get {
                return ResourceManager.GetString("lblAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string lblBtnClear {
            get {
                return ResourceManager.GetString("lblBtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string lblBtnDownload {
            get {
                return ResourceManager.GetString("lblBtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBtnSearch {
            get {
                return ResourceManager.GetString("lblBtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search condition.
        /// </summary>
        internal static string lblHeader {
            get {
                return ResourceManager.GetString("lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result list.
        /// </summary>
        internal static string lblHeaderSearchResult {
            get {
                return ResourceManager.GetString("lblHeaderSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMS.
        /// </summary>
        internal static string lblIMS {
            get {
                return ResourceManager.GetString("lblIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string lblPeriod {
            get {
                return ResourceManager.GetString("lblPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string lblReportType {
            get {
                return ResourceManager.GetString("lblReportType", resourceCulture);
            }
        }
    }
}
