//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICS120 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICS120() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ICS120", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHT document date.
        /// </summary>
        internal static string headerDocumentDate {
            get {
                return ResourceManager.GetString("headerDocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer name.
        /// </summary>
        internal static string headerPayerName {
            get {
                return ResourceManager.GetString("headerPayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment transaction no..
        /// </summary>
        internal static string headerPaymentTransNo {
            get {
                return ResourceManager.GetString("headerPaymentTransNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string headerStatus {
            get {
                return ResourceManager.GetString("headerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer name.
        /// </summary>
        internal static string headerVATRegistantName {
            get {
                return ResourceManager.GetString("headerVATRegistantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHT no.
        /// </summary>
        internal static string headerWHTNo {
            get {
                return ResourceManager.GetString("headerWHTNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string lblBtnClear {
            get {
                return ResourceManager.GetString("lblBtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBtnSearch {
            get {
                return ResourceManager.GetString("lblBtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHT document date.
        /// </summary>
        internal static string lblDocumentDate {
            get {
                return ResourceManager.GetString("lblDocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer name.
        /// </summary>
        internal static string lblPayerName {
            get {
                return ResourceManager.GetString("lblPayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment transaction no..
        /// </summary>
        internal static string lblPaymentTransactionNo {
            get {
                return ResourceManager.GetString("lblPaymentTransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search WHT.
        /// </summary>
        internal static string lblSearchWHT {
            get {
                return ResourceManager.GetString("lblSearchWHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer name.
        /// </summary>
        internal static string lblVatRegistantName {
            get {
                return ResourceManager.GetString("lblVatRegistantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHT no..
        /// </summary>
        internal static string lblWHTNo {
            get {
                return ResourceManager.GetString("lblWHTNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string MatchStatusCompleted {
            get {
                return ResourceManager.GetString("MatchStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        internal static string MatchStatusPartial {
            get {
                return ResourceManager.GetString("MatchStatusPartial", resourceCulture);
            }
        }
    }
}
