//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICS101 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICS101() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ICS101", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        internal static string btnDownloadFile {
            get {
                return ResourceManager.GetString("btnDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer address (Local).
        /// </summary>
        internal static string csvHeaderBillingClientAddressLC {
            get {
                return ResourceManager.GetString("csvHeaderBillingClientAddressLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer name (English).
        /// </summary>
        internal static string csvHeaderBillingClientNameEN {
            get {
                return ResourceManager.GetString("csvHeaderBillingClientNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer name (Local).
        /// </summary>
        internal static string csvHeaderBillingClientNameLC {
            get {
                return ResourceManager.GetString("csvHeaderBillingClientNameLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer code.
        /// </summary>
        internal static string csvHeaderBillingTargetCode {
            get {
                return ResourceManager.GetString("csvHeaderBillingTargetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection area.
        /// </summary>
        internal static string csvHeaderCollectionAreaName {
            get {
                return ResourceManager.GetString("csvHeaderCollectionAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected collect date.
        /// </summary>
        internal static string csvHeaderExpectedCollectDate {
            get {
                return ResourceManager.GetString("csvHeaderExpectedCollectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string csvHeaderMemo {
            get {
                return ResourceManager.GetString("csvHeaderMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt amount.
        /// </summary>
        internal static string csvHeaderReceiptAmount {
            get {
                return ResourceManager.GetString("csvHeaderReceiptAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt date.
        /// </summary>
        internal static string csvHeaderReceiptDate {
            get {
                return ResourceManager.GetString("csvHeaderReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt no..
        /// </summary>
        internal static string csvHeaderReceiptNo {
            get {
                return ResourceManager.GetString("csvHeaderReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result list.
        /// </summary>
        internal static string divResultList {
            get {
                return ResourceManager.GetString("divResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection area.
        /// </summary>
        internal static string lblCollectionArea {
            get {
                return ResourceManager.GetString("lblCollectionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected collect date.
        /// </summary>
        internal static string lblExpectedCollectDate {
            get {
                return ResourceManager.GetString("lblExpectedCollectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer.
        /// </summary>
        internal static string lblHeaderBillingClient {
            get {
                return ResourceManager.GetString("lblHeaderBillingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;hdrcell&quot;&gt;&lt;div&gt;Building&lt;BR&gt;(1) English&lt;BR&gt;(2) Local&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        internal static string lblHeaderBillingClientAddress {
            get {
                return ResourceManager.GetString("lblHeaderBillingClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;hdrcell&quot;&gt;&lt;div&gt;Name&lt;BR&gt;(1) English&lt;BR&gt;(2) Local&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        internal static string lblHeaderBillingClientName {
            get {
                return ResourceManager.GetString("lblHeaderBillingClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing customer code.
        /// </summary>
        internal static string lblHeaderBillingTargetCode {
            get {
                return ResourceManager.GetString("lblHeaderBillingTargetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection area.
        /// </summary>
        internal static string lblHeaderCollectionArea {
            get {
                return ResourceManager.GetString("lblHeaderCollectionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected collect date.
        /// </summary>
        internal static string lblHeaderExpectedCollectDate {
            get {
                return ResourceManager.GetString("lblHeaderExpectedCollectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string lblHeaderMemo {
            get {
                return ResourceManager.GetString("lblHeaderMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt amount.
        /// </summary>
        internal static string lblHeaderReceiptAmount {
            get {
                return ResourceManager.GetString("lblHeaderReceiptAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt date.
        /// </summary>
        internal static string lblHeaderReceiptDate {
            get {
                return ResourceManager.GetString("lblHeaderReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt no..
        /// </summary>
        internal static string lblHeaderReceiptNo {
            get {
                return ResourceManager.GetString("lblHeaderReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Delete&lt;/div&gt;.
        /// </summary>
        internal static string lblHeaderRemove {
            get {
                return ResourceManager.GetString("lblHeaderRemove", resourceCulture);
            }
        }
    }
}
