//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスによって ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションを付けて
    // /str を使用するか、または Visual Studio プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMS070 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMS070() {
        }
        
        /// <summary>
        ///   このクラスで使用されるキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMS070", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、現在のスレッドの CurrentUICulture
        ///   プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Clear に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string btnClear1 {
            get {
                return ResourceManager.GetString("btnClear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search  に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search  に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string btnSearch1 {
            get {
                return ResourceManager.GetString("btnSearch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Association に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkAssociation {
            get {
                return ResourceManager.GetString("chkAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer type に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkCustomerType {
            get {
                return ResourceManager.GetString("chkCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Existing customer に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkExistingCustomer {
            get {
                return ResourceManager.GetString("chkExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Individual に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkIndividual {
            get {
                return ResourceManager.GetString("chkIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Juristic に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkJuristic {
            get {
                return ResourceManager.GetString("chkJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New customer に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkNewCustomer {
            get {
                return ResourceManager.GetString("chkNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkOther {
            get {
                return ResourceManager.GetString("chkOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Public office に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string chkPublicOffice {
            get {
                return ResourceManager.GetString("chkPublicOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kota/Kabupaten に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboAmperKed {
            get {
                return ResourceManager.GetString("comboAmperKed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Business category に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboBusinessType {
            get {
                return ResourceManager.GetString("comboBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change type に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboChangeType {
            get {
                return ResourceManager.GetString("comboChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contract office に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboContractOffice {
            get {
                return ResourceManager.GetString("comboContractOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer role に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboCustomerRole {
            get {
                return ResourceManager.GetString("comboCustomerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provinsi に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboJangwat {
            get {
                return ResourceManager.GetString("comboJangwat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nationality に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboNationality {
            get {
                return ResourceManager.GetString("comboNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation office に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboOperationOffice {
            get {
                return ResourceManager.GetString("comboOperationOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process management status に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboProcessManagementStatus {
            get {
                return ResourceManager.GetString("comboProcessManagementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product name に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboProductName {
            get {
                return ResourceManager.GetString("comboProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start type に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboStartType {
            get {
                return ResourceManager.GetString("comboStartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;Building&lt;br /&gt;(1) English&lt;br /&gt;(2) Local&lt;/div&gt; に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerAddress {
            get {
                return ResourceManager.GetString("headerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contract no. に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerContractCode {
            get {
                return ResourceManager.GetString("headerContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Digest に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerContractDigest {
            get {
                return ResourceManager.GetString("headerContractDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service fee/Sale price に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerContractfeeSaleprice {
            get {
                return ResourceManager.GetString("headerContractfeeSaleprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;Customer&lt;br /&gt;(1) Name (English)&lt;br /&gt;(2) Name (Local)&lt;br /&gt;Premises&lt;br /&gt;(3) Name (English)&lt;br /&gt;(4) Name (Local)&lt;/div&gt; に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerContractPurchaser {
            get {
                return ResourceManager.GetString("headerContractPurchaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;(1) Contract status&lt;br /&gt;(2) Operation date/Customer acceptance date&lt;br&gt;(3) Suspension date&lt;br&gt;(4) Termination date&lt;/div&gt; に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerContractStatus {
            get {
                return ResourceManager.GetString("headerContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerCustomerCode {
            get {
                return ResourceManager.GetString("headerCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer information に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerCustomerInformation {
            get {
                return ResourceManager.GetString("headerCustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;Customer name&lt;br /&gt;(1) English&lt;br /&gt;(2) Local&lt;/div&gt; に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerCustomerName {
            get {
                return ResourceManager.GetString("headerCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of premises に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerNumberOfSite {
            get {
                return ResourceManager.GetString("headerNumberOfSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;Office&lt;br /&gt;(1) Contract&lt;br /&gt;(2) Operation&lt;/div&gt; に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerOffice {
            get {
                return ResourceManager.GetString("headerOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation date に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerOperationDate {
            get {
                return ResourceManager.GetString("headerOperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;(1) Product name&lt;br /&gt;(2) Service fee / Product price&lt;/div&gt; に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerProductName {
            get {
                return ResourceManager.GetString("headerProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rental contract に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerRentalContract {
            get {
                return ResourceManager.GetString("headerRentalContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sale contract に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerSaleContract {
            get {
                return ResourceManager.GetString("headerSaleContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Premises に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerSiteInformation {
            get {
                return ResourceManager.GetString("headerSiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;Premise&apos;s name&lt;br /&gt;(1) English&lt;br /&gt;(2) Local&lt;/div&gt; に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string headerSiteName {
            get {
                return ResourceManager.GetString("headerSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Branch name に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblBranchName {
            get {
                return ResourceManager.GetString("lblBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Termination date (Rental contract) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblCancelDate {
            get {
                return ResourceManager.GetString("lblCancelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - Cancel に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblChangeTypeSubfixCancel {
            get {
                return ResourceManager.GetString("lblChangeTypeSubfixCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - Operated に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblChangeTypeSubfixOperate {
            get {
                return ResourceManager.GetString("lblChangeTypeSubfixOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - Unoperated に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblChangeTypeSubfixUnoperate {
            get {
                return ResourceManager.GetString("lblChangeTypeSubfixUnoperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete installation date に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblCompleteInstallationDate {
            get {
                return ResourceManager.GetString("lblCompleteInstallationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contract no. に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblContractCode {
            get {
                return ResourceManager.GetString("lblContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer acceptance date (Sale contract) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblCustomerAcceptanceDate {
            get {
                return ResourceManager.GetString("lblCustomerAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblCustomerCode {
            get {
                return ResourceManager.GetString("lblCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer status  に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblCustomerStatus {
            get {
                return ResourceManager.GetString("lblCustomerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (dd/MM/yyyy) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblddMMyyyy {
            get {
                return ResourceManager.GetString("lblddMMyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fax number に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblFaxNumber {
            get {
                return ResourceManager.GetString("lblFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblGroupCode {
            get {
                return ResourceManager.GetString("lblGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group name に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblGroupName {
            get {
                return ResourceManager.GetString("lblGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NPWP に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblIDNo {
            get {
                return ResourceManager.GetString("lblIDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation date (Rental contract) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblOperationDate {
            get {
                return ResourceManager.GetString("lblOperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Planning no. に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblPlanCode {
            get {
                return ResourceManager.GetString("lblPlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblProjectCode {
            get {
                return ResourceManager.GetString("lblProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desa/Kel に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblRoad {
            get {
                return ResourceManager.GetString("lblRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salesman1 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblSalesman1 {
            get {
                return ResourceManager.GetString("lblSalesman1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Premise&apos;s code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblSiteCode {
            get {
                return ResourceManager.GetString("lblSiteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Premise&apos;s name に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblSiteName {
            get {
                return ResourceManager.GetString("lblSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jl. に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblSoi {
            get {
                return ResourceManager.GetString("lblSoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suspension date (Rental contract) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblStopDate {
            get {
                return ResourceManager.GetString("lblStopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kecamatan に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblTambolKwaeng {
            get {
                return ResourceManager.GetString("lblTambolKwaeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telephone number に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblTelephoneNumber {
            get {
                return ResourceManager.GetString("lblTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblUserCode {
            get {
                return ResourceManager.GetString("lblUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblZipCode {
            get {
                return ResourceManager.GetString("lblZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoAll {
            get {
                return ResourceManager.GetString("rdoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Billing に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoBilling {
            get {
                return ResourceManager.GetString("rdoBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contract に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoContract {
            get {
                return ResourceManager.GetString("rdoContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoCustomer {
            get {
                return ResourceManager.GetString("rdoCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rental contract (N, MA, SG) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoRentalContract {
            get {
                return ResourceManager.GetString("rdoRentalContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sale contract (Q) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoSaleContract {
            get {
                return ResourceManager.GetString("rdoSaleContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoSearchByCode {
            get {
                return ResourceManager.GetString("rdoSearchByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by condition に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string rdoSearchByCondition {
            get {
                return ResourceManager.GetString("rdoSearchByCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contract result list  に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string sectionContractResultList {
            get {
                return ResourceManager.GetString("sectionContractResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer result list  に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string sectionCustomerResultList {
            get {
                return ResourceManager.GetString("sectionCustomerResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by code に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string sectionSearchByCode {
            get {
                return ResourceManager.GetString("sectionSearchByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by condition に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string sectionSearchByCondition {
            get {
                return ResourceManager.GetString("sectionSearchByCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search contract に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string sectionSearchContract {
            get {
                return ResourceManager.GetString("sectionSearchContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search type に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string sectionSearchType {
            get {
                return ResourceManager.GetString("sectionSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify search information に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string sectionSpecifySearchInformation {
            get {
                return ResourceManager.GetString("sectionSpecifySearchInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contract information (English/Local) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string subsectionContractInformation {
            get {
                return ResourceManager.GetString("subsectionContractInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Real customer (End user)/Customer information (English/Local) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string subsectionRealCustomerContractPurchaser {
            get {
                return ResourceManager.GetString("subsectionRealCustomerContractPurchaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Premise&apos;s information (English/Local) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string subsectionSiteInformation {
            get {
                return ResourceManager.GetString("subsectionSiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string txtRole {
            get {
                return ResourceManager.GetString("txtRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string txtRoleAll {
            get {
                return ResourceManager.GetString("txtRoleAll", resourceCulture);
            }
        }
    }
}
