//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMS170 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMS170() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMS170", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent expansion.
        /// </summary>
        internal static string chkExpTypeHas {
            get {
                return ResourceManager.GetString("chkExpTypeHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child expansion.
        /// </summary>
        internal static string chkExpTypeNo {
            get {
                return ResourceManager.GetString("chkExpTypeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string chkInstFlagMain {
            get {
                return ResourceManager.GetString("chkInstFlagMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string chkInstFlagOption {
            get {
                return ResourceManager.GetString("chkInstFlagOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General equipment.
        /// </summary>
        internal static string chkInstTypeGen {
            get {
                return ResourceManager.GetString("chkInstTypeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string chkInstTypeMat {
            get {
                return ResourceManager.GetString("chkInstTypeMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring (Facility).
        /// </summary>
        internal static string chkInstTypeMon {
            get {
                return ResourceManager.GetString("chkInstTypeMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string chkProdTypeAlarm {
            get {
                return ResourceManager.GetString("chkProdTypeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string chkProdTypeSale {
            get {
                return ResourceManager.GetString("chkProdTypeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add unit price.
        /// </summary>
        internal static string headerAddUnit {
            get {
                return ResourceManager.GetString("headerAddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipmentcode.
        /// </summary>
        internal static string headerInstruCode {
            get {
                return ResourceManager.GetString("headerInstruCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment name.
        /// </summary>
        internal static string headerInstruName {
            get {
                return ResourceManager.GetString("headerInstruName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string headerNo {
            get {
                return ResourceManager.GetString("headerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental unit price.
        /// </summary>
        internal static string headerRentalUnit {
            get {
                return ResourceManager.GetString("headerRentalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale unit price.
        /// </summary>
        internal static string headerSaleUnit {
            get {
                return ResourceManager.GetString("headerSaleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Select&lt;/div&gt;.
        /// </summary>
        internal static string headerSelect {
            get {
                return ResourceManager.GetString("headerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion type.
        /// </summary>
        internal static string lblExpanFlag {
            get {
                return ResourceManager.GetString("lblExpanFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search criteria.
        /// </summary>
        internal static string lblHeader {
            get {
                return ResourceManager.GetString("lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code.
        /// </summary>
        internal static string lblInstruCode {
            get {
                return ResourceManager.GetString("lblInstruCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment flag.
        /// </summary>
        internal static string lblInstruFlag {
            get {
                return ResourceManager.GetString("lblInstruFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment name.
        /// </summary>
        internal static string lblInstruName {
            get {
                return ResourceManager.GetString("lblInstruName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment type.
        /// </summary>
        internal static string lblInstruType {
            get {
                return ResourceManager.GetString("lblInstruType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line-up type.
        /// </summary>
        internal static string lblLineUp {
            get {
                return ResourceManager.GetString("lblLineUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker.
        /// </summary>
        internal static string lblMaker {
            get {
                return ResourceManager.GetString("lblMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product type.
        /// </summary>
        internal static string lblProductType {
            get {
                return ResourceManager.GetString("lblProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result list.
        /// </summary>
        internal static string lblResultList {
            get {
                return ResourceManager.GetString("lblResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string lblSupplier {
            get {
                return ResourceManager.GetString("lblSupplier", resourceCulture);
            }
        }
    }
}
