//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMS100 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMS100() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMS100", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract (Amt).
        /// </summary>
        internal static string colAmountOfContract {
            get {
                return ResourceManager.GetString("colAmountOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract (Num).
        /// </summary>
        internal static string colNumberOfContract {
            get {
                return ResourceManager.GetString("colNumberOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer (Num).
        /// </summary>
        internal static string colNumberOfCustomer {
            get {
                return ResourceManager.GetString("colNumberOfCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premises (Num).
        /// </summary>
        internal static string colNumberOfSite {
            get {
                return ResourceManager.GetString("colNumberOfSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Address &lt;br/&gt; (1) English &lt;br/&gt; (2) Local&lt;/div&gt;.
        /// </summary>
        internal static string headerAddress {
            get {
                return ResourceManager.GetString("headerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string headerAlarm {
            get {
                return ResourceManager.GetString("headerAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Branch name &lt;br/&gt; (1) English &lt;br/&gt; (2) Local&lt;/div&gt;.
        /// </summary>
        internal static string headerBranchName {
            get {
                return ResourceManager.GetString("headerBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Customer name &lt;br/&gt; (1) English &lt;br/&gt; (2) Local&lt;/div&gt;.
        /// </summary>
        internal static string headerContaractTaget {
            get {
                return ResourceManager.GetString("headerContaractTaget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract no..
        /// </summary>
        internal static string headerContractCode {
            get {
                return ResourceManager.GetString("headerContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract digest.
        /// </summary>
        internal static string headerContractdegest {
            get {
                return ResourceManager.GetString("headerContractdegest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fee / Product price.
        /// </summary>
        internal static string headerContractfee {
            get {
                return ResourceManager.GetString("headerContractfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string headerContractTaget {
            get {
                return ResourceManager.GetString("headerContractTaget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information.
        /// </summary>
        internal static string headerCustinfo {
            get {
                return ResourceManager.GetString("headerCustinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code.
        /// </summary>
        internal static string headerCustomerCode {
            get {
                return ResourceManager.GetString("headerCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard.
        /// </summary>
        internal static string headerGuard {
            get {
                return ResourceManager.GetString("headerGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string headerMaintenance {
            get {
                return ResourceManager.GetString("headerMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string headerNo {
            get {
                return ResourceManager.GetString("headerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of contract.
        /// </summary>
        internal static string headerNumberofContract {
            get {
                return ResourceManager.GetString("headerNumberofContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of premises.
        /// </summary>
        internal static string headerNumberofSite {
            get {
                return ResourceManager.GetString("headerNumberofSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real customer (End user).
        /// </summary>
        internal static string headerRealCustomer {
            get {
                return ResourceManager.GetString("headerRealCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string headerSale {
            get {
                return ResourceManager.GetString("headerSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s code.
        /// </summary>
        internal static string headerSiteCode {
            get {
                return ResourceManager.GetString("headerSiteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s information.
        /// </summary>
        internal static string headerSiteinfo {
            get {
                return ResourceManager.GetString("headerSiteinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Premise&apos;s name &lt;br/&gt; (1) English &lt;br/&gt; (2) Local&lt;/div&gt;.
        /// </summary>
        internal static string headerSitename {
            get {
                return ResourceManager.GetString("headerSitename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group code.
        /// </summary>
        internal static string lblGroupCode {
            get {
                return ResourceManager.GetString("lblGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name (English).
        /// </summary>
        internal static string lblGroupNameEn {
            get {
                return ResourceManager.GetString("lblGroupNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name (Local).
        /// </summary>
        internal static string lblGroupNameLc {
            get {
                return ResourceManager.GetString("lblGroupNameLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract list.
        /// </summary>
        internal static string lblHeaderContractList {
            get {
                return ResourceManager.GetString("lblHeaderContractList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer group infomation.
        /// </summary>
        internal static string lblHeaderCustomerGroup {
            get {
                return ResourceManager.GetString("lblHeaderCustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer list.
        /// </summary>
        internal static string lblHeaderCustomerList {
            get {
                return ResourceManager.GetString("lblHeaderCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group summary.
        /// </summary>
        internal static string lblHeaderGroupSum {
            get {
                return ResourceManager.GetString("lblHeaderGroupSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise list.
        /// </summary>
        internal static string lblHeaderSiteList {
            get {
                return ResourceManager.GetString("lblHeaderSiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string lblMemo {
            get {
                return ResourceManager.GetString("lblMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office in charge.
        /// </summary>
        internal static string lblOffice {
            get {
                return ResourceManager.GetString("lblOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person in charge.
        /// </summary>
        internal static string lblperson {
            get {
                return ResourceManager.GetString("lblperson", resourceCulture);
            }
        }
    }
}
