//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMS260 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMS260() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMS260", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing customer.
        /// </summary>
        internal static string chkExitCustomer {
            get {
                return ResourceManager.GetString("chkExitCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer.
        /// </summary>
        internal static string chkNewCustomer {
            get {
                return ResourceManager.GetString("chkNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name (English/Local).
        /// </summary>
        internal static string CustomerName_Eng_Local {
            get {
                return ResourceManager.GetString("CustomerName_Eng_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by real customer.
        /// </summary>
        internal static string gpSearchByRealCustomer {
            get {
                return ResourceManager.GetString("gpSearchByRealCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by premises.
        /// </summary>
        internal static string gpSearchbySite {
            get {
                return ResourceManager.GetString("gpSearchbySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected real customer.
        /// </summary>
        internal static string gpSelectedRealCustomer {
            get {
                return ResourceManager.GetString("gpSelectedRealCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Select&lt;/div&gt;.
        /// </summary>
        internal static string headerButton {
            get {
                return ResourceManager.GetString("headerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Real customer (End user) name&lt;br/&gt;(1) English&lt;br/&gt;(2) Local&lt;/div&gt;.
        /// </summary>
        internal static string headerCustomerName {
            get {
                return ResourceManager.GetString("headerCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string headerNo {
            get {
                return ResourceManager.GetString("headerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Premise&apos;s building&lt;br/&gt;(1) English&lt;br/&gt;(2) Local&lt;/div&gt;.
        /// </summary>
        internal static string headerSiteAddress {
            get {
                return ResourceManager.GetString("headerSiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise’s code.
        /// </summary>
        internal static string headerSiteCode {
            get {
                return ResourceManager.GetString("headerSiteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Premise’s name&lt;br/&gt;(1) English&lt;br/&gt;(2) Local&lt;/div&gt;.
        /// </summary>
        internal static string headerSiteName {
            get {
                return ResourceManager.GetString("headerSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota/Kabupaten.
        /// </summary>
        internal static string lblAmper {
            get {
                return ResourceManager.GetString("lblAmper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code.
        /// </summary>
        internal static string lblCustomerCode {
            get {
                return ResourceManager.GetString("lblCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name (English).
        /// </summary>
        internal static string lblCustomerName_Eng {
            get {
                return ResourceManager.GetString("lblCustomerName_Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name (Local).
        /// </summary>
        internal static string lblCustomerName_Local {
            get {
                return ResourceManager.GetString("lblCustomerName_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer status.
        /// </summary>
        internal static string lblCustomerStatus {
            get {
                return ResourceManager.GetString("lblCustomerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer status *.
        /// </summary>
        internal static string lblCustomerStatus_star {
            get {
                return ResourceManager.GetString("lblCustomerStatus_star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search premise.
        /// </summary>
        internal static string lblHeader {
            get {
                return ResourceManager.GetString("lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinsi.
        /// </summary>
        internal static string lblJangwat {
            get {
                return ResourceManager.GetString("lblJangwat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result list.
        /// </summary>
        internal static string lblResultList {
            get {
                return ResourceManager.GetString("lblResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desa/Kel.
        /// </summary>
        internal static string lblRoad {
            get {
                return ResourceManager.GetString("lblRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify search condition (English/Local).
        /// </summary>
        internal static string lblSearchCondition {
            get {
                return ResourceManager.GetString("lblSearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s building (English/Local).
        /// </summary>
        internal static string lblSiteAddress_Eng_Local {
            get {
                return ResourceManager.GetString("lblSiteAddress_Eng_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise’s code.
        /// </summary>
        internal static string lblSiteCode {
            get {
                return ResourceManager.GetString("lblSiteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise’s name (English/Local).
        /// </summary>
        internal static string lblSiteName_Eng_Local {
            get {
                return ResourceManager.GetString("lblSiteName_Eng_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jl..
        /// </summary>
        internal static string lblSoi {
            get {
                return ResourceManager.GetString("lblSoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kecamatan.
        /// </summary>
        internal static string lblTambol_Kwaeng {
            get {
                return ResourceManager.GetString("lblTambol_Kwaeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s type.
        /// </summary>
        internal static string lblUsage {
            get {
                return ResourceManager.GetString("lblUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        internal static string lblZipcode {
            get {
                return ResourceManager.GetString("lblZipcode", resourceCulture);
            }
        }
    }
}
