//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMS480 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMS480() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMS480", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc. advance receive.
        /// </summary>
        internal static string headerAccAdvanceReceive {
            get {
                return ResourceManager.GetString("headerAccAdvanceReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc. unpaid.
        /// </summary>
        internal static string headerAccUnpaid {
            get {
                return ResourceManager.GetString("headerAccUnpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing code.
        /// </summary>
        internal static string headerBillingCode {
            get {
                return ResourceManager.GetString("headerBillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income date.
        /// </summary>
        internal static string headerIncomeDate {
            get {
                return ResourceManager.GetString("headerIncomeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income service fee.
        /// </summary>
        internal static string headerIncomeRentalFee {
            get {
                return ResourceManager.GetString("headerIncomeRentalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income VAT.
        /// </summary>
        internal static string headerIncomeVat {
            get {
                return ResourceManager.GetString("headerIncomeVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Year.
        /// </summary>
        internal static string headerMonthYear {
            get {
                return ResourceManager.GetString("headerMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received amount.
        /// </summary>
        internal static string headerReceivedAmount {
            get {
                return ResourceManager.GetString("headerReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid period.
        /// </summary>
        internal static string headerUnpaidPeriod {
            get {
                return ResourceManager.GetString("headerUnpaidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Code.
        /// </summary>
        internal static string lblBillingCode {
            get {
                return ResourceManager.GetString("lblBillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve carry-over &amp; profit.
        /// </summary>
        internal static string lblHeaderSearchCarryOverAndProfit {
            get {
                return ResourceManager.GetString("lblHeaderSearchCarryOverAndProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Year.
        /// </summary>
        internal static string lblMonthYear {
            get {
                return ResourceManager.GetString("lblMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string lblProductType {
            get {
                return ResourceManager.GetString("lblProductType", resourceCulture);
            }
        }
    }
}
