//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM_AJIS.DataEntity.Accounting
{
    using System;
    
    public partial class doAccountingDocumentList
    {
        public string DocumentCode { get; set; }
        public string DocumentNameENWithCode { get; set; }
        public string DocumentNameEN { get; set; }
        public string DocumentTimingType { get; set; }
        public string DocumentTimingTypeName { get; set; }
    }
}
