//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM_AJIS.DataEntity.Accounting
{
    using System;
    
    public partial class dtAccountDataOfVATReport
    {
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocNo { get; set; }
        public string BillingCilentName { get; set; }
        public string TaxID { get; set; }
        public string HeadOffice { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> AmountExVAT { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<bool> CancelFlag { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Prefix { get; set; }
        public string CurrencyType { get; set; }
    }
}
