//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class doMaintenanceCheckupInformation
    {
        #region Primitive Properties
    
        public string CheckupNo
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string ProductNameEN
        {
            get;
            set;
        }
    
        public string ProductNameJP
        {
            get;
            set;
        }
    
        public string ProductNameLC
        {
            get;
            set;
        }
    
        public string RealCustomerCustCode
        {
            get;
            set;
        }
    
        public string SiteCode
        {
            get;
            set;
        }
    
        public string UserCode
        {
            get;
            set;
        }
    
        public string RealCustomerNameEN
        {
            get;
            set;
        }
    
        public string RealCustomerNameLC
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }

        #endregion

    }
}
