//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class doMaintenanceCheckSheetReport
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string UserCode
        {
            get;
            set;
        }
    
        public string MaintenanceMonth
        {
            get;
            set;
        }
    
        public string MaintenanceYear
        {
            get;
            set;
        }
    
        public string ContractTargetNameEN
        {
            get;
            set;
        }
    
        public string ContractTargetNameLC
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }
    
        public string SecurityTypeCode
        {
            get;
            set;
        }
    
        public string NextMaintenanceMonth
        {
            get;
            set;
        }
    
        public string NextMaintenanceYear
        {
            get;
            set;
        }
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public Nullable<int> Qty
        {
            get;
            set;
        }
    
        public string Type
        {
            get;
            set;
        }
    
        public string CheckupNo
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string QuotationTargetCode
        {
            get;
            set;
        }
    
        public string QuotationAlphabet
        {
            get;
            set;
        }
    
        public string ContractOfficeCode
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string ContractTargetCustCode
        {
            get;
            set;
        }
    
        public int RowsPerPage
        {
            get;
            set;
        }
    
        public string OperationOfficeNameEN
        {
            get;
            set;
        }
    
        public string OperationOfficeNameJP
        {
            get;
            set;
        }
    
        public string OperationOfficeNameLC
        {
            get;
            set;
        }

        #endregion

    }
}
