//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class doProjectContractDetail
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string ProductCode
        {
            get;
            set;
        }
    
        public string ProductNameEN
        {
            get;
            set;
        }
    
        public string ProductNameJP
        {
            get;
            set;
        }
    
        public string ProductNameLC
        {
            get;
            set;
        }
    
        public Nullable<decimal> Fee
        {
            get;
            set;
        }
    
        public string DocAuditResultCode
        {
            get;
            set;
        }
    
        public string DocAuditResultNameEN
        {
            get;
            set;
        }
    
        public string DocAuditResultNameJP
        {
            get;
            set;
        }
    
        public string DocAuditResultNameLC
        {
            get;
            set;
        }
    
        public string ServiceTypeCode
        {
            get;
            set;
        }
    
        public string ContractStatus
        {
            get;
            set;
        }
    
        public Nullable<decimal> FeeUsd
        {
            get;
            set;
        }
    
        public string FeeCurrencyType
        {
            get;
            set;
        }

        #endregion

    }
}
