//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtARListCTS370
    {
        #region Primitive Properties
    
        public string RequestNo
        {
            get;
            set;
        }
    
        public string ApproveNo
        {
            get;
            set;
        }
    
        public string AROfficeCode
        {
            get;
            set;
        }
    
        public Nullable<bool> hasRespondingDetailFlag
        {
            get;
            set;
        }
    
        public string ARStatus
        {
            get;
            set;
        }
    
        public string ARStatusCode
        {
            get;
            set;
        }
    
        public string ARStatusNameEN
        {
            get;
            set;
        }
    
        public string ARStatusNameLC
        {
            get;
            set;
        }
    
        public string ARStatusNameJP
        {
            get;
            set;
        }
    
        public string ARRelavantType
        {
            get;
            set;
        }
    
        public string CustCode
        {
            get;
            set;
        }
    
        public Nullable<bool> RelatedToAllSiteFlag
        {
            get;
            set;
        }
    
        public string SiteCode
        {
            get;
            set;
        }
    
        public Nullable<bool> RelatedToAllContractFlag
        {
            get;
            set;
        }
    
        public string ProjectCode
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string QuotationTargetCode
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> ApprovedDate
        {
            get;
            set;
        }
    
        public string ARType
        {
            get;
            set;
        }
    
        public string ARTypeCode
        {
            get;
            set;
        }
    
        public string ARTypeNameEN
        {
            get;
            set;
        }
    
        public string ARTypeNameLC
        {
            get;
            set;
        }
    
        public string ARTypeNameJP
        {
            get;
            set;
        }
    
        public Nullable<bool> ImportanceFlag
        {
            get;
            set;
        }
    
        public string ARPurpose
        {
            get;
            set;
        }
    
        public string ApprEmpFirstNameEN
        {
            get;
            set;
        }
    
        public string ApprEmpLastNameEN
        {
            get;
            set;
        }
    
        public string ApprEmpFirstNameLC
        {
            get;
            set;
        }
    
        public string ApprEmpLastNameLC
        {
            get;
            set;
        }
    
        public string ReqEmpNo
        {
            get;
            set;
        }
    
        public string ReqEmpFirstNameEN
        {
            get;
            set;
        }
    
        public string ReqEmpLastNameEN
        {
            get;
            set;
        }
    
        public string ReqEmpFirstNameLC
        {
            get;
            set;
        }
    
        public string ReqEmpLastNameLC
        {
            get;
            set;
        }
    
        public string AudEmpNo
        {
            get;
            set;
        }
    
        public string AudEmpFirstNameEN
        {
            get;
            set;
        }
    
        public string AudEmpLastNameEN
        {
            get;
            set;
        }
    
        public string AudEmpFirstNameLC
        {
            get;
            set;
        }
    
        public string AudEmpLastNameLC
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> DueDateDeadLine
        {
            get;
            set;
        }
    
        public string CustFullNameEN
        {
            get;
            set;
        }
    
        public string CustFullNameLC
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }
    
        public string ContractTargetPurchaseCustFullNameEN
        {
            get;
            set;
        }
    
        public string ContractTargetPurchaseCustFullNameLC
        {
            get;
            set;
        }
    
        public string ProjectName
        {
            get;
            set;
        }
    
        public string QuotationTargetCustFullNameEN
        {
            get;
            set;
        }
    
        public string QuotationTargetCustFullNameLC
        {
            get;
            set;
        }
    
        public string DueDateDeadLineTime
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public string ApprEmpNo
        {
            get;
            set;
        }
    
        public string ApprEmpNameEN
        {
            get;
            set;
        }
    
        public string ApprEmpNameLC
        {
            get;
            set;
        }
    
        public string ReqEmpNameEN
        {
            get;
            set;
        }
    
        public string ReqEmpNameLC
        {
            get;
            set;
        }
    
        public string AudEmpNameEN
        {
            get;
            set;
        }
    
        public string AudEmpNameLC
        {
            get;
            set;
        }
    
        public string ARTitleType
        {
            get;
            set;
        }

        #endregion

    }
}
