//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtContractSignerType
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string ContractSignerTypeCode
        {
            get;
            set;
        }
    
        public string ContractSignerTypeName
        {
            get;
            set;
        }
    
        public string ContractSignerTypeNameEN
        {
            get;
            set;
        }
    
        public string ContractSignerTypeNameJP
        {
            get;
            set;
        }
    
        public string ContractSignerTypeNameLC
        {
            get;
            set;
        }

        #endregion

    }
}
