//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtContractDocument
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string ContractDocOCC
        {
            get;
            set;
        }
    
        public string DocumentCode
        {
            get;
            set;
        }
    
        public string DocumentType
        {
            get;
            set;
        }
    
        public string DocumentTypeNameEN
        {
            get;
            set;
        }
    
        public string DocumentTypeNameJP
        {
            get;
            set;
        }
    
        public string DocumentTypeNameLC
        {
            get;
            set;
        }
    
        public string DocumentNameEN
        {
            get;
            set;
        }
    
        public string DocumentNameJP
        {
            get;
            set;
        }
    
        public string DocumentNameLC
        {
            get;
            set;
        }
    
        public string ContractOfficeCode
        {
            get;
            set;
        }
    
        public string ContractOfficeNameEN
        {
            get;
            set;
        }
    
        public string ContractOfficeNameJP
        {
            get;
            set;
        }
    
        public string ContractOfficeNameLC
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string OperationOfficeNameEN
        {
            get;
            set;
        }
    
        public string OperationOfficeNameJP
        {
            get;
            set;
        }
    
        public string OperationOfficeNameLC
        {
            get;
            set;
        }
    
        public string DocStatus
        {
            get;
            set;
        }
    
        public string DocStatusNameEN
        {
            get;
            set;
        }
    
        public string DocStatusNameJP
        {
            get;
            set;
        }
    
        public string DocStatusNameLC
        {
            get;
            set;
        }
    
        public string DocAuditResult
        {
            get;
            set;
        }
    
        public string DocAuditResultNameEN
        {
            get;
            set;
        }
    
        public string DocAuditResultNameJP
        {
            get;
            set;
        }
    
        public string DocAuditResultNameLC
        {
            get;
            set;
        }
    
        public string NegotiationStaffEmpNo
        {
            get;
            set;
        }
    
        public string NegotiationStaffEmpFirstNameEN
        {
            get;
            set;
        }
    
        public string NegotiationStaffEmpLastNameEN
        {
            get;
            set;
        }
    
        public string NegotiationStaffEmpFirstNameLC
        {
            get;
            set;
        }
    
        public string NegotiationStaffEmpLastNameLC
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CollectDocDate
        {
            get;
            set;
        }
    
        public string CoverLetterDocCode
        {
            get;
            set;
        }
    
        public string RealCustomerCustCode
        {
            get;
            set;
        }
    
        public string RealCustomerNameLC
        {
            get;
            set;
        }
    
        public string RealCustomerNameEN
        {
            get;
            set;
        }
    
        public string CreateOfficeNameEN
        {
            get;
            set;
        }
    
        public string CreateOfficeNameLC
        {
            get;
            set;
        }
    
        public string ProductNameEN
        {
            get;
            set;
        }
    
        public string ProductNameLC
        {
            get;
            set;
        }
    
        public string PhoneLineTypeNameEN
        {
            get;
            set;
        }
    
        public string PhoneLineTypeNameLC
        {
            get;
            set;
        }
    
        public string PhoneLineOwnerTypeNameEN
        {
            get;
            set;
        }
    
        public string PhoneLineOwnerTypeNameLC
        {
            get;
            set;
        }
    
        public Nullable<bool> FacilityMonitorFlag
        {
            get;
            set;
        }
    
        public string BusinessTypeNameEN
        {
            get;
            set;
        }
    
        public string BusinessTypeNameLC
        {
            get;
            set;
        }
    
        public string BuildingUsageNameEN
        {
            get;
            set;
        }
    
        public string BuildingUsageNameLC
        {
            get;
            set;
        }

        #endregion

    }
}
