//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtRentalHistoryDigest
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string ContractType
        {
            get;
            set;
        }
    
        public System.DateTime RegistrationDate
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> OperationDueDate
        {
            get;
            set;
        }
    
        public string ChangeType
        {
            get;
            set;
        }
    
        public string ChangeTypeNameEN
        {
            get;
            set;
        }
    
        public string ChangeTypeNameJP
        {
            get;
            set;
        }
    
        public string ChangeTypeNameLC
        {
            get;
            set;
        }
    
        public string IncidentARType
        {
            get;
            set;
        }
    
        public string IncidentARTypeNameEN
        {
            get;
            set;
        }
    
        public string IncidentARTypeNameJP
        {
            get;
            set;
        }
    
        public string IncidentARTypeNameLC
        {
            get;
            set;
        }
    
        public decimal ContractFee
        {
            get;
            set;
        }
    
        public Nullable<decimal> OrderInstallFee
        {
            get;
            set;
        }
    
        public string DocAuditResult
        {
            get;
            set;
        }
    
        public string DocAuditResultNameEN
        {
            get;
            set;
        }
    
        public string DocAuditResultNameJP
        {
            get;
            set;
        }
    
        public string DocAuditResultNameLC
        {
            get;
            set;
        }
    
        public string DocumentCode
        {
            get;
            set;
        }
    
        public string DocumentNameEN
        {
            get;
            set;
        }
    
        public string DocumentNameJP
        {
            get;
            set;
        }
    
        public string DocumentNameLC
        {
            get;
            set;
        }
    
        public Nullable<int> IncidentID
        {
            get;
            set;
        }
    
        public string RequestNo
        {
            get;
            set;
        }
    
        public string ApproveNo
        {
            get;
            set;
        }
    
        public string ContractFeeCurrencyType
        {
            get;
            set;
        }
    
        public string OrderInstallFeeCurrencyType
        {
            get;
            set;
        }

        #endregion

    }
}
