//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtRelatedContract
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string RelatedContractCode
        {
            get;
            set;
        }
    
        public string ServiceTypeCode
        {
            get;
            set;
        }
    
        public string ProductCode
        {
            get;
            set;
        }
    
        public string ProductNameEN
        {
            get;
            set;
        }
    
        public string ProductNameJP
        {
            get;
            set;
        }
    
        public string ProductNameLC
        {
            get;
            set;
        }
    
        public Nullable<decimal> Price
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CustAcceptanceDate
        {
            get;
            set;
        }
    
        public string ProductName
        {
            get;
            set;
        }
    
        public string RelatedOCC
        {
            get;
            set;
        }
    
        public string PriceCurrencyType
        {
            get;
            set;
        }

        #endregion

    }
}
