//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtSearchDraftContractResult
    {
        #region Primitive Properties
    
        public string QuotationCode
        {
            get;
            set;
        }
    
        public string QuotationTargetCode
        {
            get;
            set;
        }
    
        public string Alphabet
        {
            get;
            set;
        }
    
        public string ContractTargetCode
        {
            get;
            set;
        }
    
        public string ContractTargetNameEN
        {
            get;
            set;
        }
    
        public string ContractTargetNameLC
        {
            get;
            set;
        }
    
        public string SiteCode
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }
    
        public string ContractOfficeCode
        {
            get;
            set;
        }
    
        public string ContractOfficeNameEN
        {
            get;
            set;
        }
    
        public string ContractOfficeNameLC
        {
            get;
            set;
        }
    
        public string ContractOfficeNameJP
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string OperationOfficeNameEN
        {
            get;
            set;
        }
    
        public string OperationOfficeNameLC
        {
            get;
            set;
        }
    
        public string OperationOfficeNameJP
        {
            get;
            set;
        }
    
        public string Salesman1Code
        {
            get;
            set;
        }
    
        public string Salesman1NameEN
        {
            get;
            set;
        }
    
        public string Salesman1NameLC
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> RegisterDate
        {
            get;
            set;
        }
    
        public string ApprovalStatusCode
        {
            get;
            set;
        }
    
        public string ApprovalStatusNameEN
        {
            get;
            set;
        }
    
        public string ApprovalStatusNameLC
        {
            get;
            set;
        }
    
        public string ApprovalStatusNameJP
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> ApproveContractDate
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string ProductTypeCode
        {
            get;
            set;
        }
    
        public string ProductTypeCodeName
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }

        #endregion

    }
}
