//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtTbt_ProjectPurchaserCustomerForView
    {
        #region Primitive Properties
    
        public string ProjectCode
        {
            get;
            set;
        }
    
        public string CustCode
        {
            get;
            set;
        }
    
        public string CustNameEN
        {
            get;
            set;
        }
    
        public string CustNameLC
        {
            get;
            set;
        }
    
        public string CustFullNameEN
        {
            get;
            set;
        }
    
        public string CustFullNameLC
        {
            get;
            set;
        }
    
        public string RepPersonName
        {
            get;
            set;
        }
    
        public string ContactPersonName
        {
            get;
            set;
        }
    
        public string SECOMContactPerson
        {
            get;
            set;
        }
    
        public string CustTypeCode
        {
            get;
            set;
        }
    
        public string CompanyTypeCode
        {
            get;
            set;
        }
    
        public string FinancialMarketTypeCode
        {
            get;
            set;
        }
    
        public string BusinessTypeCode
        {
            get;
            set;
        }
    
        public string PhoneNo
        {
            get;
            set;
        }
    
        public string IDNo
        {
            get;
            set;
        }
    
        public string RegionCode
        {
            get;
            set;
        }
    
        public string URL
        {
            get;
            set;
        }
    
        public string AddressFullEN
        {
            get;
            set;
        }
    
        public string AddressEN
        {
            get;
            set;
        }
    
        public string AlleyEN
        {
            get;
            set;
        }
    
        public string RoadEN
        {
            get;
            set;
        }
    
        public string SubDistrictEN
        {
            get;
            set;
        }
    
        public string AddressFullLC
        {
            get;
            set;
        }
    
        public string AddressLC
        {
            get;
            set;
        }
    
        public string AlleyLC
        {
            get;
            set;
        }
    
        public string RoadLC
        {
            get;
            set;
        }
    
        public string SubDistrictLC
        {
            get;
            set;
        }
    
        public string DistrictCode
        {
            get;
            set;
        }
    
        public string ProvinceCode
        {
            get;
            set;
        }
    
        public string ZipCode
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public string CreateBy
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public string UpdateBy
        {
            get;
            set;
        }
    
        public string ProvinceNameLC
        {
            get;
            set;
        }
    
        public string ProvinceNameEN
        {
            get;
            set;
        }
    
        public string DistrictNameEN
        {
            get;
            set;
        }
    
        public string DistrictNameLC
        {
            get;
            set;
        }
    
        public string BusinessTypeNameEN
        {
            get;
            set;
        }
    
        public string BusinessTypeNameJP
        {
            get;
            set;
        }
    
        public string BusinessTypeNameLC
        {
            get;
            set;
        }
    
        public string CompanyTypeNameEN
        {
            get;
            set;
        }
    
        public string CompanyTypeNameLC
        {
            get;
            set;
        }
    
        public string NationalityEN
        {
            get;
            set;
        }
    
        public string NationalityLC
        {
            get;
            set;
        }
    
        public string NationalityJP
        {
            get;
            set;
        }

        #endregion

    }
}
