//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class dtTbs_IncidentTypePattern
    {
        #region Primitive Properties
    
        public string IncidentType
        {
            get;
            set;
        }
    
        public string IncidentTypeContentEN
        {
            get;
            set;
        }
    
        public string IncidentTypeContentLC
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public string CreateBy
        {
            get;
            set;
        }
    
        public string UpdateDate
        {
            get;
            set;
        }
    
        public string UpdateBy
        {
            get;
            set;
        }

        #endregion

    }
}
