//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Contract
{
    public partial class RPTConfirmCurrInstMemoDo
    {
        #region Primitive Properties
    
        public string PrintDate
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string RealInvestigationDate
        {
            get;
            set;
        }
    
        public string CustomerSignatureName
        {
            get;
            set;
        }
    
        public string EmployeeName
        {
            get;
            set;
        }
    
        public string EmployeePosition
        {
            get;
            set;
        }
    
        public string ImageSignaturePath
        {
            get;
            set;
        }
    
        public string DocumentVersion
        {
            get;
            set;
        }
    
        public string DocNo
        {
            get;
            set;
        }
    
        public int DocID
        {
            get;
            set;
        }
    
        public string DocumentCode
        {
            get;
            set;
        }
    
        public string QuotationTargetCode
        {
            get;
            set;
        }
    
        public string Alphabet
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string ContractDocOCC
        {
            get;
            set;
        }
    
        public string ContractOfficeCode
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string DocumentNameEN
        {
            get;
            set;
        }
    
        public string DocumentNameLC
        {
            get;
            set;
        }
    
        public string ContractTargetNameEN
        {
            get;
            set;
        }
    
        public string RealCustomerNameEN
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteAddressEN
        {
            get;
            set;
        }
    
        public string CompanyName
        {
            get;
            set;
        }

        #endregion

    }
}
