//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IVS080 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IVS080() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IVS080", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Rack no..
        /// </summary>
        internal static string headerDestinationShelfNo {
            get {
                return ResourceManager.GetString("headerDestinationShelfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code.
        /// </summary>
        internal static string headerInstrumentCode {
            get {
                return ResourceManager.GetString("headerInstrumentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment name.
        /// </summary>
        internal static string headerInstrumentName {
            get {
                return ResourceManager.GetString("headerInstrumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Remove&lt;/div&gt;.
        /// </summary>
        internal static string headerRemove {
            get {
                return ResourceManager.GetString("headerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Add&lt;/div&gt;.
        /// </summary>
        internal static string headerSelect {
            get {
                return ResourceManager.GetString("headerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no..
        /// </summary>
        internal static string headerShelfNo {
            get {
                return ResourceManager.GetString("headerShelfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Rack no..
        /// </summary>
        internal static string headerSourceShelfNo {
            get {
                return ResourceManager.GetString("headerSourceShelfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock qty.
        /// </summary>
        internal static string headerStockQuantity {
            get {
                return ResourceManager.GetString("headerStockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer qty.
        /// </summary>
        internal static string headerTransferQuantity {
            get {
                return ResourceManager.GetString("headerTransferQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve no..
        /// </summary>
        internal static string lblApproveNo {
            get {
                return ResourceManager.GetString("lblApproveNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string lblBtnClear {
            get {
                return ResourceManager.GetString("lblBtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download slip.
        /// </summary>
        internal static string lblBtnDownloadSlip {
            get {
                return ResourceManager.GetString("lblBtnDownloadSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New register.
        /// </summary>
        internal static string lblBtnNewRegister {
            get {
                return ResourceManager.GetString("lblBtnNewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBtnSearch {
            get {
                return ResourceManager.GetString("lblBtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract no..
        /// </summary>
        internal static string lblContractCode {
            get {
                return ResourceManager.GetString("lblContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination area.
        /// </summary>
        internal static string lblDestinationArea {
            get {
                return ResourceManager.GetString("lblDestinationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination location.
        /// </summary>
        internal static string lblDestinationLocation {
            get {
                return ResourceManager.GetString("lblDestinationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code.
        /// </summary>
        internal static string lblInstrumentCode {
            get {
                return ResourceManager.GetString("lblInstrumentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment name.
        /// </summary>
        internal static string lblInstrumentName {
            get {
                return ResourceManager.GetString("lblInstrumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string lblMemo {
            get {
                return ResourceManager.GetString("lblMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string lblOffice {
            get {
                return ResourceManager.GetString("lblOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search equipment.
        /// </summary>
        internal static string lblSearchInstrument {
            get {
                return ResourceManager.GetString("lblSearchInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search equipment list .
        /// </summary>
        internal static string lblSearchInstrumentList {
            get {
                return ResourceManager.GetString("lblSearchInstrumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no..
        /// </summary>
        internal static string lblShelfNo {
            get {
                return ResourceManager.GetString("lblShelfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show slip no..
        /// </summary>
        internal static string lblShowSlipNo {
            get {
                return ResourceManager.GetString("lblShowSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slip no..
        /// </summary>
        internal static string lblSlipNo {
            get {
                return ResourceManager.GetString("lblSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source area.
        /// </summary>
        internal static string lblSourceArea {
            get {
                return ResourceManager.GetString("lblSourceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify office and area.
        /// </summary>
        internal static string lblSpecifyOffice {
            get {
                return ResourceManager.GetString("lblSpecifyOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer date.
        /// </summary>
        internal static string lblTransferDate {
            get {
                return ResourceManager.GetString("lblTransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer equipment detail.
        /// </summary>
        internal static string lblTransferInstrumentDetail {
            get {
                return ResourceManager.GetString("lblTransferInstrumentDetail", resourceCulture);
            }
        }
    }
}
