//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Inventory
{
    public partial class doIVR180
    {
        #region Primitive Properties
    
        public string SlipNo
        {
            get;
            set;
        }
    
        public string SlipIssueDate
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string InstallationSlipNo
        {
            get;
            set;
        }
    
        public string ProjectCode
        {
            get;
            set;
        }
    
        public string ApproveNo
        {
            get;
            set;
        }
    
        public string SourceOfficeCode
        {
            get;
            set;
        }
    
        public string DestinationOfficeCode
        {
            get;
            set;
        }
    
        public string Memo
        {
            get;
            set;
        }
    
        public string SourceOfficeName
        {
            get;
            set;
        }
    
        public string DestOfficeName
        {
            get;
            set;
        }
    
        public string SourceLocationName
        {
            get;
            set;
        }
    
        public string DestLocationName
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string OperationOfficeName
        {
            get;
            set;
        }
    
        public string SiteName
        {
            get;
            set;
        }
    
        public string SubContractorName
        {
            get;
            set;
        }
    
        public string SourceAreaName
        {
            get;
            set;
        }
    
        public string DestAreaName
        {
            get;
            set;
        }
    
        public string SourceShelfNo
        {
            get;
            set;
        }
    
        public string DestShelfNo
        {
            get;
            set;
        }
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public string InstrumentName
        {
            get;
            set;
        }
    
        public int TransferQty
        {
            get;
            set;
        }
    
        public string StockInDate
        {
            get;
            set;
        }
    
        public string StockOutDate
        {
            get;
            set;
        }
    
        public string CustFullNameEN
        {
            get;
            set;
        }
    
        public string AddressFullEN
        {
            get;
            set;
        }

        #endregion

    }
}
