//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Inventory
{
    public partial class doResultIVS200
    {
        #region Primitive Properties
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public string InstrumentName
        {
            get;
            set;
        }
    
        public int CurrentQty
        {
            get;
            set;
        }
    
        public int OrderQty
        {
            get;
            set;
        }
    
        public int BookingQty
        {
            get;
            set;
        }
    
        public int EffectiveQty
        {
            get;
            set;
        }
    
        public int SafetyQty
        {
            get;
            set;
        }

        #endregion

    }
}
