//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Inventory
{
    public partial class dtInprocessToInstallReportDetail
    {
        #region Primitive Properties
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> InstallCompleteDate
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> OperateDate
        {
            get;
            set;
        }
    
        public string CustNameEN
        {
            get;
            set;
        }
    
        public string CustNameLC
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> TransferDate
        {
            get;
            set;
        }
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public Nullable<int> Qty
        {
            get;
            set;
        }
    
        public decimal UnitPrice
        {
            get;
            set;
        }
    
        public Nullable<decimal> Amount
        {
            get;
            set;
        }
    
        public string ChangeType
        {
            get;
            set;
        }
    
        public Nullable<decimal> OrderSalePrice
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }
    
        public Nullable<decimal> AmountUsD
        {
            get;
            set;
        }
    
        public string InstallationSlipNo
        {
            get;
            set;
        }
    
        public decimal UnitPriceUsD
        {
            get;
            set;
        }

        #endregion

    }
}
