//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Inventory
{
    public partial class dtResultIVS220
    {
        #region Primitive Properties
    
        public string MoveType
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> TransferDate
        {
            get;
            set;
        }
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public string InstrumentName
        {
            get;
            set;
        }
    
        public string AreaNameShort
        {
            get;
            set;
        }
    
        public string AreaNameEN
        {
            get;
            set;
        }
    
        public string AreaNameJP
        {
            get;
            set;
        }
    
        public string AreaNameLC
        {
            get;
            set;
        }
    
        public Nullable<int> TransferQty
        {
            get;
            set;
        }
    
        public string SlipId
        {
            get;
            set;
        }
    
        public string InventorySlipNo
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string SupplierNameEN
        {
            get;
            set;
        }
    
        public string SupplierNameLC
        {
            get;
            set;
        }
    
        public Nullable<decimal> UnitPrice
        {
            get;
            set;
        }
    
        public Nullable<decimal> TotalCost
        {
            get;
            set;
        }
    
        public string CustFullNameEN
        {
            get;
            set;
        }
    
        public string CustFullNameLC
        {
            get;
            set;
        }
    
        public string PurchaseOrderNo
        {
            get;
            set;
        }
    
        public string Memo
        {
            get;
            set;
        }

        #endregion

    }
}
