//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Inventory
{
    public partial class tbt_InventoryProjectWIP
    {
        #region Primitive Properties
    
        public virtual string ProjectCode
        {
            get;
            set;
        }
    
        public virtual string AreaCode
        {
            get;
            set;
        }
    
        public virtual string InstrumentCode
        {
            get;
            set;
        }
    
        public virtual Nullable<int> InstrumentQty
        {
            get;
            set;
        }

        #endregion

    }
}
