//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CTS040 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CTS040() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CTS040", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval status.
        /// </summary>
        internal static string cboApprovalStatus {
            get {
                return ResourceManager.GetString("cboApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract office.
        /// </summary>
        internal static string cboContractOffice {
            get {
                return ResourceManager.GetString("cboContractOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation office.
        /// </summary>
        internal static string cboOperationOffice {
            get {
                return ResourceManager.GetString("cboOperationOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App. status.
        /// </summary>
        internal static string headerApprovalStatus {
            get {
                return ResourceManager.GetString("headerApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string headerAudit {
            get {
                return ResourceManager.GetString("headerAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract no..
        /// </summary>
        internal static string headerContractCode {
            get {
                return ResourceManager.GetString("headerContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Customer&lt;br /&gt;(1)  Customer code&lt;br /&gt;(2) Name (English)&lt;br /&gt;(3) Name (Local)&lt;/div&gt;.
        /// </summary>
        internal static string headerContractTargetPurchaser {
            get {
                return ResourceManager.GetString("headerContractTargetPurchaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP-01 registration date.
        /// </summary>
        internal static string headerCPRegistrationDate {
            get {
                return ResourceManager.GetString("headerCPRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Office&lt;br /&gt;(1) Contract&lt;br /&gt;(2) Operation&lt;/div&gt;.
        /// </summary>
        internal static string headerOffice {
            get {
                return ResourceManager.GetString("headerOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation code.
        /// </summary>
        internal static string headerQuotationCode {
            get {
                return ResourceManager.GetString("headerQuotationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FN-99/FQ-99 registration date.
        /// </summary>
        internal static string headerRegistrationDate {
            get {
                return ResourceManager.GetString("headerRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Registration date&lt;br /&gt;(1) FN-99/FQ-99&lt;br /&gt;(2) CP-01&lt;/div&gt;.
        /// </summary>
        internal static string headerRegistrationFNFQCP {
            get {
                return ResourceManager.GetString("headerRegistrationFNFQCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Salesman 1&lt;br /&gt;(1) Code&lt;br /&gt;(2) Name&lt;/div&gt;.
        /// </summary>
        internal static string headerSalesman1 {
            get {
                return ResourceManager.GetString("headerSalesman1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Premise&lt;br /&gt;(1) Premise’s code&lt;br /&gt; (2) Name (English)&lt;br /&gt;(3) Name (Local)&lt;/div&gt;.
        /// </summary>
        internal static string headerSite {
            get {
                return ResourceManager.GetString("headerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        internal static string lblAlphabet {
            get {
                return ResourceManager.GetString("lblAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval result search criteria.
        /// </summary>
        internal static string lblApprovalResultSearchCriteria {
            get {
                return ResourceManager.GetString("lblApprovalResultSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        internal static string lblContractTargetName {
            get {
                return ResourceManager.GetString("lblContractTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP-01 registration date.
        /// </summary>
        internal static string lblCPRegistrationDate {
            get {
                return ResourceManager.GetString("lblCPRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ddMMyyyy).
        /// </summary>
        internal static string lblddMMyyyy {
            get {
                return ResourceManager.GetString("lblddMMyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation code.
        /// </summary>
        internal static string lblQuotationCode {
            get {
                return ResourceManager.GetString("lblQuotationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation target code.
        /// </summary>
        internal static string lblQuotationTargetCode {
            get {
                return ResourceManager.GetString("lblQuotationTargetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FN-99/FQ-99 registration date.
        /// </summary>
        internal static string lblRegistrationDate {
            get {
                return ResourceManager.GetString("lblRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FN-99/FQ-99 registration date (from).
        /// </summary>
        internal static string lblRegistrationDateFrom {
            get {
                return ResourceManager.GetString("lblRegistrationDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FN-99/FQ-99 registration date (to).
        /// </summary>
        internal static string lblRegistrationDateTo {
            get {
                return ResourceManager.GetString("lblRegistrationDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman 1 code.
        /// </summary>
        internal static string lblSalesman1Code {
            get {
                return ResourceManager.GetString("lblSalesman1Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman 1 name.
        /// </summary>
        internal static string lblSalesman1Name {
            get {
                return ResourceManager.GetString("lblSalesman1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search FN-99/FQ-99.
        /// </summary>
        internal static string lblSearchFN99FQ99 {
            get {
                return ResourceManager.GetString("lblSearchFN99FQ99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result list.
        /// </summary>
        internal static string lblSearchResult {
            get {
                return ResourceManager.GetString("lblSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise’s name.
        /// </summary>
        internal static string lblSiteName {
            get {
                return ResourceManager.GetString("lblSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string lblTildeSymbol {
            get {
                return ResourceManager.GetString("lblTildeSymbol", resourceCulture);
            }
        }
    }
}
