//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Master
{
    public partial class doGetTbm_Site
    {
        #region Primitive Properties
    
        public string SiteCode
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }
    
        public string AddressFullEN
        {
            get;
            set;
        }
    
        public string AddressFullLC
        {
            get;
            set;
        }
    
        public string AddressEN
        {
            get;
            set;
        }
    
        public string AddressLC
        {
            get;
            set;
        }
    
        public string SECOMContactPerson
        {
            get;
            set;
        }
    
        public string PersonInCharge
        {
            get;
            set;
        }
    
        public string BuildingUsageCode
        {
            get;
            set;
        }
    
        public string PhoneNo
        {
            get;
            set;
        }
    
        public string AlleyEN
        {
            get;
            set;
        }
    
        public string AlleyLC
        {
            get;
            set;
        }
    
        public string RoadEN
        {
            get;
            set;
        }
    
        public string RoadLC
        {
            get;
            set;
        }
    
        public string SubDistrictEN
        {
            get;
            set;
        }
    
        public string SubDistrictLC
        {
            get;
            set;
        }
    
        public string ProvinceCode
        {
            get;
            set;
        }
    
        public string DistrictCode
        {
            get;
            set;
        }
    
        public string ZipCode
        {
            get;
            set;
        }
    
        public string CustCode
        {
            get;
            set;
        }
    
        public string SiteNo
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public string CreateBy
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public string UpdateBy
        {
            get;
            set;
        }

        #endregion

    }
}
