//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Master
{
    public partial class dtAuthorizeOffice
    {
        #region Primitive Properties
    
        public string OfficeCode
        {
            get;
            set;
        }
    
        public string OfficeNameEN
        {
            get;
            set;
        }
    
        public string OfficeNameJP
        {
            get;
            set;
        }
    
        public string OfficeNameLC
        {
            get;
            set;
        }
    
        public string FunctionLogistic
        {
            get;
            set;
        }
    
        public string FunctionSecurity
        {
            get;
            set;
        }
    
        public string FunctionSale
        {
            get;
            set;
        }
    
        public string FunctionAdmin
        {
            get;
            set;
        }
    
        public string FunctionBilling
        {
            get;
            set;
        }
    
        public string FunctionQuatation
        {
            get;
            set;
        }
    
        public string FunctionDebtTracing
        {
            get;
            set;
        }

        #endregion

    }
}
