//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Master
{
    public partial class dtEmpNo
    {
        #region Primitive Properties
    
        public string EmpNo
        {
            get;
            set;
        }
    
        public string EmpFirstNameEN
        {
            get;
            set;
        }
    
        public string EmpLastNameEN
        {
            get;
            set;
        }
    
        public string EmpFirstNameLC
        {
            get;
            set;
        }
    
        public string EmpLastNameLC
        {
            get;
            set;
        }
    
        public string EmployeeNameDisplay
        {
            get;
            set;
        }

        #endregion

    }
}
