//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Master
{
    public partial class dtPermissionHeader
    {
        #region Primitive Properties
    
        public string crPermissionGroupCode
        {
            get;
            set;
        }
    
        public string crPermissionGroupName
        {
            get;
            set;
        }
    
        public string crPermissionIndividualCode
        {
            get;
            set;
        }
    
        public string crPermissionIndividualName
        {
            get;
            set;
        }
    
        public string crOfficeCode
        {
            get;
            set;
        }
    
        public string crDepartmentCode
        {
            get;
            set;
        }
    
        public string crPositionCode
        {
            get;
            set;
        }
    
        public string OfficeNameEN
        {
            get;
            set;
        }
    
        public string OfficeNameJP
        {
            get;
            set;
        }
    
        public string OfficeNameLC
        {
            get;
            set;
        }
    
        public string DepartmentName
        {
            get;
            set;
        }
    
        public string PositionName
        {
            get;
            set;
        }
    
        public Nullable<bool> Quotation
        {
            get;
            set;
        }
    
        public Nullable<bool> Contract
        {
            get;
            set;
        }
    
        public Nullable<bool> Install
        {
            get;
            set;
        }
    
        public Nullable<bool> Inventory
        {
            get;
            set;
        }
    
        public Nullable<bool> Billing
        {
            get;
            set;
        }
    
        public Nullable<bool> Income
        {
            get;
            set;
        }
    
        public Nullable<bool> Common
        {
            get;
            set;
        }
    
        public Nullable<bool> Master
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public string PermissionTypeEN
        {
            get;
            set;
        }
    
        public string PermissionTypeLC
        {
            get;
            set;
        }
    
        public string PermissionTypeJP
        {
            get;
            set;
        }
    
        public string PermissionTypeCode
        {
            get;
            set;
        }

        #endregion

    }
}
