//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Master
{
    public partial class tbm_Object
    {
        #region Primitive Properties
    
        public virtual string ObjectID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ModuleID
        {
            get;
            set;
        }
    
        public virtual string ObjectNameEN
        {
            get;
            set;
        }
    
        public virtual string ObjectNameJP
        {
            get;
            set;
        }
    
        public virtual string ObjectNameLC
        {
            get;
            set;
        }
    
        public virtual string ObjectTypeCode
        {
            get;
            set;
        }
    
        public virtual string ObjectDescriptionEN
        {
            get;
            set;
        }
    
        public virtual string ObjectDescriptionJP
        {
            get;
            set;
        }
    
        public virtual string ObjectDescriptionLC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual string CreateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual string UpdateBy
        {
            get;
            set;
        }
    
        public virtual string SubObjectID
        {
            get;
            set;
        }
    
        public virtual string ObjectAbbrNameEN
        {
            get;
            set;
        }
    
        public virtual string ObjectAbbrNameJP
        {
            get;
            set;
        }
    
        public virtual string ObjectAbbrNameLC
        {
            get;
            set;
        }

        #endregion

    }
}
