//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Master
{
    public partial class tbm_Product
    {
        #region Primitive Properties
    
        public virtual string ProductCode
        {
            get;
            set;
        }
    
        public virtual string ProductTypeCode
        {
            get;
            set;
        }
    
        public virtual string ProductNameEN
        {
            get;
            set;
        }
    
        public virtual string ProductNameJP
        {
            get;
            set;
        }
    
        public virtual string ProductNameLC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SalesStartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SalesEndDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LifeCycle
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DepreciationPeriodContract
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DepreciationPeriodRevenue
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual string CreateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual string UpdateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> OneShotFlag
        {
            get;
            set;
        }

        #endregion

    }
}
