//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Common
{
    public partial class doMiscTypeCode
    {
        #region Primitive Properties
    
        public string FieldName
        {
            get;
            set;
        }
    
        public string ValueCode
        {
            get;
            set;
        }
    
        public string ValueDescription
        {
            get;
            set;
        }
    
        public string ValueDisplayEN
        {
            get;
            set;
        }
    
        public string ValueDisplayJP
        {
            get;
            set;
        }
    
        public string ValueDisplayLC
        {
            get;
            set;
        }

        #endregion

    }
}
