//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Common
{
    public partial class dtDocumentData
    {
        #region Primitive Properties
    
        public string DocumentNameEN
        {
            get;
            set;
        }
    
        public string DocumentNameJP
        {
            get;
            set;
        }
    
        public string DocumentNameLC
        {
            get;
            set;
        }
    
        public string ContractOfficeCode
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string BillingOfficeCode
        {
            get;
            set;
        }
    
        public string IssueOfficeCode
        {
            get;
            set;
        }
    
        public string DocumentNo
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string QuotationTargetCode
        {
            get;
            set;
        }
    
        public string Alphabet
        {
            get;
            set;
        }
    
        public string ContractBillingTargetCode
        {
            get;
            set;
        }
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public Nullable<int> Month
        {
            get;
            set;
        }
    
        public Nullable<int> Year
        {
            get;
            set;
        }
    
        public string FilePath
        {
            get;
            set;
        }
    
        public Nullable<int> DownloadCount
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> GenerateDate
        {
            get;
            set;
        }
    
        public string DocumentName
        {
            get;
            set;
        }
    
        public string DocumentCode
        {
            get;
            set;
        }
    
        public string ConOfficeCodeName
        {
            get;
            set;
        }
    
        public string ConOfficeCodeNameEN
        {
            get;
            set;
        }
    
        public string ConOfficeCodeNameJP
        {
            get;
            set;
        }
    
        public string ConOfficeCodeNameLC
        {
            get;
            set;
        }
    
        public string OperOfficeCodeName
        {
            get;
            set;
        }
    
        public string OperOfficeCodeNameEN
        {
            get;
            set;
        }
    
        public string OperOfficeCodeNameJP
        {
            get;
            set;
        }
    
        public string OperOfficeCodeNameLC
        {
            get;
            set;
        }
    
        public string BillOfficeCodeName
        {
            get;
            set;
        }
    
        public string BillOfficeCodeNameEN
        {
            get;
            set;
        }
    
        public string BillOfficeCodeNameJP
        {
            get;
            set;
        }
    
        public string BillOfficeCodeNameLC
        {
            get;
            set;
        }
    
        public string IssueOfficeCodeName
        {
            get;
            set;
        }
    
        public string IssueOfficeCodeNameEN
        {
            get;
            set;
        }
    
        public string IssueOfficeCodeNameJP
        {
            get;
            set;
        }
    
        public string IssueOfficeCodeNameLC
        {
            get;
            set;
        }
    
        public string DocumentOCC
        {
            get;
            set;
        }
    
        public string LocationCode
        {
            get;
            set;
        }

        #endregion

    }
}
