//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Common
{
    public partial class dtDocumentList
    {
        #region Primitive Properties
    
        public string DocumentNo
        {
            get;
            set;
        }
    
        public string DocumentOCC
        {
            get;
            set;
        }
    
        public string DocumentCode
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string OCC
        {
            get;
            set;
        }
    
        public string QuotationTargetCode
        {
            get;
            set;
        }
    
        public string Alphabet
        {
            get;
            set;
        }
    
        public string ProjectCode
        {
            get;
            set;
        }
    
        public string BillingTargetCode
        {
            get;
            set;
        }
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public string ContractOfficeCode
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string BillingOfficeCode
        {
            get;
            set;
        }
    
        public string IssueOfficeCode
        {
            get;
            set;
        }
    
        public Nullable<int> ReportMonth
        {
            get;
            set;
        }
    
        public Nullable<int> ReportYear
        {
            get;
            set;
        }
    
        public string FilePath
        {
            get;
            set;
        }
    
        public Nullable<int> DownloadCount
        {
            get;
            set;
        }
    
        public Nullable<int> ManagementNo
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public string CreateBy
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public string UpdateBy
        {
            get;
            set;
        }

        #endregion

    }
}
