//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Common
{
    public partial class tbm_Supplier
    {
        #region Primitive Properties
    
        public virtual string SupplierCode
        {
            get;
            set;
        }
    
        public virtual string SupplierNameEN
        {
            get;
            set;
        }
    
        public virtual string SupplierNameLC
        {
            get;
            set;
        }
    
        public virtual string RegionCode
        {
            get;
            set;
        }
    
        public virtual string PhoneNo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual string CreateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual string UpdateBy
        {
            get;
            set;
        }
    
        public virtual string BankName
        {
            get;
            set;
        }
    
        public virtual string AccountName
        {
            get;
            set;
        }
    
        public virtual string AccountNo
        {
            get;
            set;
        }
    
        public virtual string AddressFullEN
        {
            get;
            set;
        }
    
        public virtual string AddressFullLC
        {
            get;
            set;
        }
    
        public virtual string FaxNo
        {
            get;
            set;
        }

        #endregion

    }
}
