//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Installation
{
    public partial class RPTNewRentalSlipDo
    {
        #region Primitive Properties
    
        public string SlipIssueDate
        {
            get;
            set;
        }
    
        public string SlipNo
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string PlanCode
        {
            get;
            set;
        }
    
        public string MaintenanceNo
        {
            get;
            set;
        }
    
        public string ExpectedInstrumentArrivalDate
        {
            get;
            set;
        }
    
        public string UserCode
        {
            get;
            set;
        }
    
        public string PreviousSlipNo
        {
            get;
            set;
        }
    
        public int OtherSubContractor
        {
            get;
            set;
        }
    
        public string InstrumentCode
        {
            get;
            set;
        }
    
        public int CurrentStockOutQty
        {
            get;
            set;
        }
    
        public int TotalStockOutQty
        {
            get;
            set;
        }
    
        public int ReturnQty
        {
            get;
            set;
        }
    
        public int ContractInstalledQty
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string SlipIssueOfficeCode
        {
            get;
            set;
        }
    
        public string InstallationMemo
        {
            get;
            set;
        }
    
        public string OfficeNameEN
        {
            get;
            set;
        }
    
        public string SubContractorNameEN
        {
            get;
            set;
        }
    
        public string ContractTargetNameEN
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string AddressFullEN
        {
            get;
            set;
        }
    
        public string StockOutTypeEN
        {
            get;
            set;
        }

        #endregion

    }
}
