//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Installation
{
    public partial class RPTPOSubPriceDo
    {
        #region Primitive Properties
    
        public string Salesman1
        {
            get;
            set;
        }
    
        public string DepartmentName
        {
            get;
            set;
        }
    
        public string PlanCode
        {
            get;
            set;
        }
    
        public string IssueDate
        {
            get;
            set;
        }
    
        public string InstallationSiteName
        {
            get;
            set;
        }
    
        public string ProductName
        {
            get;
            set;
        }
    
        public string Address
        {
            get;
            set;
        }
    
        public string PhoneNo
        {
            get;
            set;
        }
    
        public string Fax
        {
            get;
            set;
        }
    
        public string OperationOfficeName
        {
            get;
            set;
        }
    
        public string ProposeInstallStartDate
        {
            get;
            set;
        }
    
        public string ContractStartDate
        {
            get;
            set;
        }
    
        public string InstallationTypeName
        {
            get;
            set;
        }
    
        public string BuildingUsageNameLC
        {
            get;
            set;
        }
    
        public string SubcontractorCode
        {
            get;
            set;
        }
    
        public string MaintenanceNo
        {
            get;
            set;
        }
    
        public string ContractProjectCode
        {
            get;
            set;
        }
    
        public string ProjectName
        {
            get;
            set;
        }
    
        public string ServiceTypeCode
        {
            get;
            set;
        }
    
        public string SubContractorName
        {
            get;
            set;
        }
    
        public string OperationOfficeCode
        {
            get;
            set;
        }
    
        public string CustomerStaffName
        {
            get;
            set;
        }
    
        public string CustomerStaffBelonging
        {
            get;
            set;
        }
    
        public string CustomerStaffPhoneNo
        {
            get;
            set;
        }
    
        public decimal ActualPOAmount
        {
            get;
            set;
        }
    
        public string SpecialInstallationFlag
        {
            get;
            set;
        }
    
        public string BuildingTypeCode
        {
            get;
            set;
        }
    
        public string CeilingTypeTBar
        {
            get;
            set;
        }
    
        public string CeilingTypeSlabConcrete
        {
            get;
            set;
        }
    
        public string CeilingTypeMBar
        {
            get;
            set;
        }
    
        public string CeilingTypeSteel
        {
            get;
            set;
        }
    
        public string HasCeilingHeight
        {
            get;
            set;
        }
    
        public decimal CeilingHeight
        {
            get;
            set;
        }
    
        public string SpecialInsPVC
        {
            get;
            set;
        }
    
        public string SpecialInsSLN
        {
            get;
            set;
        }
    
        public string SpecialInsProtector
        {
            get;
            set;
        }
    
        public string SpecialInsEMT
        {
            get;
            set;
        }
    
        public string SpecialInsPE
        {
            get;
            set;
        }
    
        public string SpecialInsOther
        {
            get;
            set;
        }
    
        public string SpecialInsOtherText
        {
            get;
            set;
        }
    
        public int POAmountRevision
        {
            get;
            set;
        }
    
        public string SubContractorAddress
        {
            get;
            set;
        }
    
        public System.DateTime registerDate
        {
            get;
            set;
        }
    
        public decimal VatRate
        {
            get;
            set;
        }
    
        public string POMemo
        {
            get;
            set;
        }

        #endregion

    }
}
