//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Income
{
    public partial class doGetICR050_Detail
    {
        #region Primitive Properties
    
        public string MatchID
        {
            get;
            set;
        }
    
        public Nullable<decimal> BankFeeAmount
        {
            get;
            set;
        }
    
        public Nullable<decimal> OtherExpenseAmount
        {
            get;
            set;
        }
    
        public Nullable<decimal> OtherIncomeAmount
        {
            get;
            set;
        }
    
        public string InvoiceNo
        {
            get;
            set;
        }
    
        public int InvoiceOCC
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> IssueInvDate
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> AutoTransferDate
        {
            get;
            set;
        }
    
        public string BillingTargetCode
        {
            get;
            set;
        }
    
        public Nullable<decimal> InvoiceAmount
        {
            get;
            set;
        }
    
        public Nullable<decimal> PaidAmountIncVat
        {
            get;
            set;
        }
    
        public Nullable<decimal> VatRate
        {
            get;
            set;
        }
    
        public Nullable<decimal> VatAmount
        {
            get;
            set;
        }
    
        public Nullable<decimal> WHTRate
        {
            get;
            set;
        }
    
        public Nullable<decimal> WHTAmount
        {
            get;
            set;
        }
    
        public Nullable<decimal> RegisteredWHTAmount
        {
            get;
            set;
        }
    
        public string InvoicePaymentStatus
        {
            get;
            set;
        }
    
        public Nullable<bool> IssueInvFlag
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> FirstIssueInvDate
        {
            get;
            set;
        }
    
        public Nullable<bool> FirstIssueInvFlag
        {
            get;
            set;
        }
    
        public string PaymentMethod
        {
            get;
            set;
        }
    
        public string CorrectReason
        {
            get;
            set;
        }
    
        public string RefOldInvoiceNo
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public string CreateBy
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public string UpdateBy
        {
            get;
            set;
        }
    
        public string ReasonForFailure
        {
            get;
            set;
        }
    
        public string BillingTypeCode
        {
            get;
            set;
        }
    
        public string ExemptApproveNo
        {
            get;
            set;
        }
    
        public string AutoTransferFile
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> TaxInvoiceDate
        {
            get;
            set;
        }

        #endregion

    }
}
