//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Income
{
    public partial class doRptReceipt
    {
        #region Primitive Properties
    
        public string ReceiptNo
        {
            get;
            set;
        }
    
        public string TaxInvoiceNo
        {
            get;
            set;
        }
    
        public string ReceiptDate
        {
            get;
            set;
        }
    
        public string ReceiptDate_Buddhist
        {
            get;
            set;
        }
    
        public string BillingTargetCode
        {
            get;
            set;
        }
    
        public string BillingClientNameEN
        {
            get;
            set;
        }
    
        public string BillingClientNameLC
        {
            get;
            set;
        }
    
        public string BillingClientAddressEN
        {
            get;
            set;
        }
    
        public string BillingClientAddressLC
        {
            get;
            set;
        }
    
        public string InvoiceNo
        {
            get;
            set;
        }
    
        public int InvoiceOCC
        {
            get;
            set;
        }
    
        public decimal ReceiptAmount
        {
            get;
            set;
        }
    
        public string AdvanceReceiptStatus
        {
            get;
            set;
        }
    
        public bool CancelFlag
        {
            get;
            set;
        }
    
        public string PaymentType
        {
            get;
            set;
        }
    
        public string PaymentDate
        {
            get;
            set;
        }
    
        public string PaymentDate_Buddhist
        {
            get;
            set;
        }
    
        public string PaymentMatchingDate
        {
            get;
            set;
        }
    
        public string PaymentMatchingDate_Buddhist
        {
            get;
            set;
        }
    
        public decimal InvoiceAmount
        {
            get;
            set;
        }
    
        public decimal VATRate
        {
            get;
            set;
        }
    
        public decimal VATAmount
        {
            get;
            set;
        }
    
        public decimal WHTAmount
        {
            get;
            set;
        }
    
        public string ShowIssueDate
        {
            get;
            set;
        }
    
        public string DocLanguage
        {
            get;
            set;
        }
    
        public string IssueInvDate
        {
            get;
            set;
        }
    
        public string IssueInvDate_Buddhist
        {
            get;
            set;
        }
    
        public string BillingOfficeCode
        {
            get;
            set;
        }
    
        public string SeparateInvType
        {
            get;
            set;
        }
    
        public string ContractCode
        {
            get;
            set;
        }
    
        public string BillingOCC
        {
            get;
            set;
        }
    
        public int BillingDetailNo
        {
            get;
            set;
        }
    
        public string BillingTypeCode
        {
            get;
            set;
        }
    
        public decimal BillingAmount
        {
            get;
            set;
        }
    
        public string BillingStartDate
        {
            get;
            set;
        }
    
        public string BillingStartDate_Buddhist
        {
            get;
            set;
        }
    
        public string BillingEndDate
        {
            get;
            set;
        }
    
        public string BillingEndDate_Buddhist
        {
            get;
            set;
        }
    
        public bool FirstFeeFlag
        {
            get;
            set;
        }
    
        public string InvoiceDescriptionEN
        {
            get;
            set;
        }
    
        public string InvoiceDescriptionLC
        {
            get;
            set;
        }
    
        public string SortingType
        {
            get;
            set;
        }
    
        public string BillingTypeGroup
        {
            get;
            set;
        }
    
        public string SiteCode
        {
            get;
            set;
        }
    
        public string SiteNameEN
        {
            get;
            set;
        }
    
        public string SiteNameLC
        {
            get;
            set;
        }
    
        public int Page
        {
            get;
            set;
        }
    
        public string SignatureType
        {
            get;
            set;
        }
    
        public string EmpName
        {
            get;
            set;
        }
    
        public string EmpPosition
        {
            get;
            set;
        }
    
        public string ImageFileName
        {
            get;
            set;
        }
    
        public string RealBillingClientNameEN
        {
            get;
            set;
        }
    
        public string RealBillingClientNameLC
        {
            get;
            set;
        }
    
        public string RealBillingClientAddressEN
        {
            get;
            set;
        }
    
        public string RealBillingClientAddressLC
        {
            get;
            set;
        }
    
        public string SuppleInvAddress
        {
            get;
            set;
        }
    
        public string BillingOffceNameLC
        {
            get;
            set;
        }
    
        public string IDNo
        {
            get;
            set;
        }
    
        public string BranchNameEN
        {
            get;
            set;
        }
    
        public string BranchNameLC
        {
            get;
            set;
        }
    
        public string BranchNo
        {
            get;
            set;
        }
    
        public string BillingClientCode
        {
            get;
            set;
        }
    
        public string BillingAmountCurrencyType
        {
            get;
            set;
        }
    
        public decimal BillingAmountUsd
        {
            get;
            set;
        }
    
        public decimal InvoiceAmountUsd
        {
            get;
            set;
        }
    
        public string InvoiceAmountCurrencyType
        {
            get;
            set;
        }
    
        public decimal VatAmountUsd
        {
            get;
            set;
        }
    
        public string VatAmountCurrencyType
        {
            get;
            set;
        }
    
        public string BillingOfficeNameEN
        {
            get;
            set;
        }

        #endregion

    }
}
