//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Income
{
    public partial class tbt_MoneyCollectionInfo
    {
        #region Primitive Properties
    
        public virtual string ReceiptNo
        {
            get;
            set;
        }
    
        public virtual string CollectionArea
        {
            get;
            set;
        }
    
        public virtual System.DateTime ExpectedCollectDate
        {
            get;
            set;
        }
    
        public virtual string Memo
        {
            get;
            set;
        }
    
        public virtual string CreateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual string UpdateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual string BillingTargetCode
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ReceiptDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> ReceiptAmount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> ReceiptAmountUsd
        {
            get;
            set;
        }
    
        public virtual string ReceiptAmountCurrencyType
        {
            get;
            set;
        }

        #endregion

    }
}
