//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SECOM_AJIS.DataEntity.Income
{
    public partial class tbt_PaymentImportFile
    {
        #region Primitive Properties
    
        public virtual System.Guid ImportID
        {
            get;
            set;
        }
    
        public virtual string PaymentType
        {
            get;
            set;
        }
    
        public virtual int SECOMAccountID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PaymentDate
        {
            get;
            set;
        }
    
        public virtual string FilePath
        {
            get;
            set;
        }
    
        public virtual string FileName
        {
            get;
            set;
        }
    
        public virtual string CreateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual string UpdateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }

        #endregion

    }
}
