//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM_AJIS.Presentation.Inventory.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM_AJIS.Presentation.Inventory.Message.MessageList", typeof(MessageList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching result.
        /// </summary>
        internal static string MSG4001 {
            get {
                return ResourceManager.GetString("MSG4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process to freeze data for stock checking does not run..
        /// </summary>
        internal static string MSG4002 {
            get {
                return ResourceManager.GetString("MSG4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start stock checking process does not run..
        /// </summary>
        internal static string MSG4003 {
            get {
                return ResourceManager.GetString("MSG4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result more than 1,000 records. Please input new search criteria..
        /// </summary>
        internal static string MSG4004 {
            get {
                return ResourceManager.GetString("MSG4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected equipment is duplicate..
        /// </summary>
        internal static string MSG4005 {
            get {
                return ResourceManager.GetString("MSG4005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data for transferring..
        /// </summary>
        internal static string MSG4006 {
            get {
                return ResourceManager.GetString("MSG4006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring quantity of {0} must be more than 0..
        /// </summary>
        internal static string MSG4007 {
            get {
                return ResourceManager.GetString("MSG4007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment: {0}, transfer quantity is more than current equipment quantity..
        /// </summary>
        internal static string MSG4008 {
            get {
                return ResourceManager.GetString("MSG4008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment: {0}, there is no data on source location..
        /// </summary>
        internal static string MSG4009 {
            get {
                return ResourceManager.GetString("MSG4009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated inventory slip no. is over limit. Please contact the administrator..
        /// </summary>
        internal static string MSG4010 {
            get {
                return ResourceManager.GetString("MSG4010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search slip no. ,{0}, not found..
        /// </summary>
        internal static string MSG4011 {
            get {
                return ResourceManager.GetString("MSG4011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no. ,{0}, was received..
        /// </summary>
        internal static string MSG4012 {
            get {
                return ResourceManager.GetString("MSG4012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to confirm receive equipment?.
        /// </summary>
        internal static string MSG4013 {
            get {
                return ResourceManager.GetString("MSG4013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Source office] and [Destination office] must not be same office..
        /// </summary>
        internal static string MSG4014 {
            get {
                return ResourceManager.GetString("MSG4014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify rack no.(from) as character come before rack no.(to) in alphabetical order..
        /// </summary>
        internal static string MSG4015 {
            get {
                return ResourceManager.GetString("MSG4015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get Headquarter office of inventory. Please contact the administrator..
        /// </summary>
        internal static string MSG4016 {
            get {
                return ResourceManager.GetString("MSG4016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot input ‘Supplier code’ and ‘Supplier name’ together..
        /// </summary>
        internal static string MSG4017 {
            get {
                return ResourceManager.GetString("MSG4017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer type of this Slip no. is incorrect..
        /// </summary>
        internal static string MSG4018 {
            get {
                return ResourceManager.GetString("MSG4018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register completed..
        /// </summary>
        internal static string MSG4019 {
            get {
                return ResourceManager.GetString("MSG4019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Order quantity&apos; must be inputted more than 0..
        /// </summary>
        internal static string MSG4020 {
            get {
                return ResourceManager.GetString("MSG4020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add equipment data more than 15 rows..
        /// </summary>
        internal static string MSG4021 {
            get {
                return ResourceManager.GetString("MSG4021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have clicked &apos;Enter&apos; key more than 4 times in a row in [Memo] text box..
        /// </summary>
        internal static string MSG4022 {
            get {
                return ResourceManager.GetString("MSG4022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data in [Installation] list. Do you want to continue this process?.
        /// </summary>
        internal static string MSG4023 {
            get {
                return ResourceManager.GetString("MSG4023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is sample equipment in purchase order. Do you want to continue this process?.
        /// </summary>
        internal static string MSG4024 {
            get {
                return ResourceManager.GetString("MSG4024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Modify order qty&apos; must more than or equal to &apos;Receive qty&apos;..
        /// </summary>
        internal static string MSG4025 {
            get {
                return ResourceManager.GetString("MSG4025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Modify order qty&apos; must less than or equal &apos;First order qty&apos;..
        /// </summary>
        internal static string MSG4026 {
            get {
                return ResourceManager.GetString("MSG4026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel purchase order will be confirmed. Do you want to continue?.
        /// </summary>
        internal static string MSG4027 {
            get {
                return ResourceManager.GetString("MSG4027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current &apos;Purchase order status&apos; on DB is not &apos;Wait to receive&apos;..
        /// </summary>
        internal static string MSG4028 {
            get {
                return ResourceManager.GetString("MSG4028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Transfer equipment quantity&apos; must be inputted more than 0..
        /// </summary>
        internal static string MSG4029 {
            get {
                return ResourceManager.GetString("MSG4029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment: {0}, &apos;Stock-out qty&apos; must be inputted more than 0..
        /// </summary>
        internal static string MSG4030 {
            get {
                return ResourceManager.GetString("MSG4030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment: {0},&apos;Repair return qty&apos; must be inputted more than 0..
        /// </summary>
        internal static string MSG4031 {
            get {
                return ResourceManager.GetString("MSG4031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Purchase order status]  on DB is not &apos;Completed&apos;..
        /// </summary>
        internal static string MSG4032 {
            get {
                return ResourceManager.GetString("MSG4032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Modify order qty] must be equal or more than [Receive qty]..
        /// </summary>
        internal static string MSG4033 {
            get {
                return ResourceManager.GetString("MSG4033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment code: {0}, [Receive qty] must be equal or less than [Remain qty]..
        /// </summary>
        internal static string MSG4034 {
            get {
                return ResourceManager.GetString("MSG4034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of [Receive qty] must be more than 0..
        /// </summary>
        internal static string MSG4035 {
            get {
                return ResourceManager.GetString("MSG4035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of [Stock-in equipment qty] must be more than 0..
        /// </summary>
        internal static string MSG4036 {
            get {
                return ResourceManager.GetString("MSG4036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputted equipment code has not been registered in equipment master of this system. Please check whether there is a mistake or not..
        /// </summary>
        internal static string MSG4037 {
            get {
                return ResourceManager.GetString("MSG4037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code is already in list..
        /// </summary>
        internal static string MSG4038 {
            get {
                return ResourceManager.GetString("MSG4038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code and equipment area is already in list..
        /// </summary>
        internal static string MSG4039 {
            get {
                return ResourceManager.GetString("MSG4039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Stock-in equipment qty] must be inputted more than 0..
        /// </summary>
        internal static string MSG4040 {
            get {
                return ResourceManager.GetString("MSG4040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [In Date] must be less than or equal to [Out Date]..
        /// </summary>
        internal static string MSG4041 {
            get {
                return ResourceManager.GetString("MSG4041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Create date (from)] must be less than or equal to [Create date (to)]..
        /// </summary>
        internal static string MSG4042 {
            get {
                return ResourceManager.GetString("MSG4042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel slip?.
        /// </summary>
        internal static string MSG4043 {
            get {
                return ResourceManager.GetString("MSG4043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month of [Stock-in date] must be equal to current month..
        /// </summary>
        internal static string MSG4044 {
            get {
                return ResourceManager.GetString("MSG4044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment {0}, Area {1}, Current equipment qty must be equal to or more than [Stock-in equipment qty]..
        /// </summary>
        internal static string MSG4045 {
            get {
                return ResourceManager.GetString("MSG4045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-in slip no. must not ever been registered asset..
        /// </summary>
        internal static string MSG4046 {
            get {
                return ResourceManager.GetString("MSG4046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no., {0}, Equipment code, {1}, &apos;Transfer qty&apos; must be inputted more than 0. .
        /// </summary>
        internal static string MSG4047 {
            get {
                return ResourceManager.GetString("MSG4047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputted rack no. {0} is mistake. It does not exist in rack master..
        /// </summary>
        internal static string MSG4048 {
            get {
                return ResourceManager.GetString("MSG4048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rack no., {0}, Equipment code, {1}, &apos;Destination rack no.&apos; must be inputted value. .
        /// </summary>
        internal static string MSG4049 {
            get {
                return ResourceManager.GetString("MSG4049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no., {0}, Equipment code, {1}, Cannot input Rack no. for temporary receive (00) in ‘Destination rack no.’.
        /// </summary>
        internal static string MSG4050 {
            get {
                return ResourceManager.GetString("MSG4050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify slip no..
        /// </summary>
        internal static string MSG4051 {
            get {
                return ResourceManager.GetString("MSG4051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment total price] must more than 0..
        /// </summary>
        internal static string MSG4052 {
            get {
                return ResourceManager.GetString("MSG4052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no., {0}, Equipment code, {1}, Cannot input destination rack no. same as source rack no..
        /// </summary>
        internal static string MSG4053 {
            get {
                return ResourceManager.GetString("MSG4053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no. {0}, Equipment code, {1}, Cannot transfer to difference area..
        /// </summary>
        internal static string MSG4054 {
            get {
                return ResourceManager.GetString("MSG4054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rackno., {0}, Equipment code, {1}, Cannot move rack because there is rack refer to the same area and same equipment exiting..
        /// </summary>
        internal static string MSG4055 {
            get {
                return ResourceManager.GetString("MSG4055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no., {0}, Equipment code, {1}, Must input [Transfer qty] = [Stock qty] in case move normal rack to empty rack..
        /// </summary>
        internal static string MSG4056 {
            get {
                return ResourceManager.GetString("MSG4056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MSG4057 {
            get {
                return ResourceManager.GetString("MSG4057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no., {0}, Equipment code, {1}, [Transfer qty] is more than [Stock qty]..
        /// </summary>
        internal static string MSG4058 {
            get {
                return ResourceManager.GetString("MSG4058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no., {0}, Equipment code, {1}, There is no data on this location..
        /// </summary>
        internal static string MSG4059 {
            get {
                return ResourceManager.GetString("MSG4059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Picking list Slip no. is over limit. Please contact to administrator..
        /// </summary>
        internal static string MSG4060 {
            get {
                return ResourceManager.GetString("MSG4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Expected stock-out date (from)] must be less than or equal [Expected stock-out date (to)].
        /// </summary>
        internal static string MSG4061 {
            get {
                return ResourceManager.GetString("MSG4061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected [installation slip no.] is duplicate..
        /// </summary>
        internal static string MSG4062 {
            get {
                return ResourceManager.GetString("MSG4062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to generate picking list..
        /// </summary>
        internal static string MSG4063 {
            get {
                return ResourceManager.GetString("MSG4063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation slip, {0}, was registered picking list..
        /// </summary>
        internal static string MSG4064 {
            get {
                return ResourceManager.GetString("MSG4064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get installation slip information..
        /// </summary>
        internal static string MSG4065 {
            get {
                return ResourceManager.GetString("MSG4065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify [Project code] before retrieve project information..
        /// </summary>
        internal static string MSG4066 {
            get {
                return ResourceManager.GetString("MSG4066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Project code ,{0}, not found..
        /// </summary>
        internal static string MSG4067 {
            get {
                return ResourceManager.GetString("MSG4067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data for calculate..
        /// </summary>
        internal static string MSG4068 {
            get {
                return ResourceManager.GetString("MSG4068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment code, {0}, must be inputted value more than 0..
        /// </summary>
        internal static string MSG4069 {
            get {
                return ResourceManager.GetString("MSG4069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project status is not &quot;Processing&quot;..
        /// </summary>
        internal static string MSG4070 {
            get {
                return ResourceManager.GetString("MSG4070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Fix returned qty] must be inputted more than 0..
        /// </summary>
        internal static string MSG4071 {
            get {
                return ResourceManager.GetString("MSG4071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to confirm &apos;Start checking&apos;?.
        /// </summary>
        internal static string MSG4072 {
            get {
                return ResourceManager.GetString("MSG4072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start checing inventory because &apos;Checking status&apos; is not &apos;Preparing&apos;..
        /// </summary>
        internal static string MSG4073 {
            get {
                return ResourceManager.GetString("MSG4073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to confirm &apos;Stop checking&apos;?.
        /// </summary>
        internal static string MSG4074 {
            get {
                return ResourceManager.GetString("MSG4074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start checing inventory because &apos;Checking status&apos; is not &apos;Implementing&apos;..
        /// </summary>
        internal static string MSG4075 {
            get {
                return ResourceManager.GetString("MSG4075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Purchase order no. is over limit. Please contact to administrator..
        /// </summary>
        internal static string MSG4076 {
            get {
                return ResourceManager.GetString("MSG4076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot input [Checking date] over range of &apos;Start checking date({0})&apos; and &apos;Current date&apos;..
        /// </summary>
        internal static string MSG4077 {
            get {
                return ResourceManager.GetString("MSG4077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking equipment slip data not found..
        /// </summary>
        internal static string MSG4078 {
            get {
                return ResourceManager.GetString("MSG4078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no, {0}, is not matching with equipment area..
        /// </summary>
        internal static string MSG4079 {
            get {
                return ResourceManager.GetString("MSG4079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot input empty rack..
        /// </summary>
        internal static string MSG4080 {
            get {
                return ResourceManager.GetString("MSG4080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added equipment data is duplicate..
        /// </summary>
        internal static string MSG4081 {
            get {
                return ResourceManager.GetString("MSG4081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data for checking equipment..
        /// </summary>
        internal static string MSG4082 {
            get {
                return ResourceManager.GetString("MSG4082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rack no., {0}, Equipment area, {1}, Equipment code, {2}, must be inputted value on [Checking equipment quantity]..
        /// </summary>
        internal static string MSG4083 {
            get {
                return ResourceManager.GetString("MSG4083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search checking equipment data not found..
        /// </summary>
        internal static string MSG4084 {
            get {
                return ResourceManager.GetString("MSG4084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search installation slip for stock-out data not found..
        /// </summary>
        internal static string MSG4085 {
            get {
                return ResourceManager.GetString("MSG4085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, cannot stock-out because [New inst. sale] more than current equipment qty..
        /// </summary>
        internal static string MSG4086 {
            get {
                return ResourceManager.GetString("MSG4086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, Cannot stock-out because [New inst. sample] more than current equipment qty..
        /// </summary>
        internal static string MSG4087 {
            get {
                return ResourceManager.GetString("MSG4087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, Cannot stock-out because [New inst. rental] more than current equipment qty..
        /// </summary>
        internal static string MSG4088 {
            get {
                return ResourceManager.GetString("MSG4088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, Cannot stock-out because [Secondhand inst. rental] more than current equipment qty..
        /// </summary>
        internal static string MSG4089 {
            get {
                return ResourceManager.GetString("MSG4089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stock out equipment code, {0} because   [Total stock-out qty] not equal to summary Qty of stock-out equipment of each area. Please adjust stock-out qty to be the same value..
        /// </summary>
        internal static string MSG4090 {
            get {
                return ResourceManager.GetString("MSG4090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of first stock-out, summary Qty of stock-out equipment must not be equal to [Remain stock-out qty]. If you want to stock-out all kind &amp; qty of equipments, please use ‘IVS020:Register stock-out for installation’ screen..
        /// </summary>
        internal static string MSG4091 {
            get {
                return ResourceManager.GetString("MSG4091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment code, {0}, Summary Qty of stock-out equipment must be less than equal to [Remain stock-out qty]..
        /// </summary>
        internal static string MSG4092 {
            get {
                return ResourceManager.GetString("MSG4092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Inventory Lot no. is over limit. Please contact to administrator..
        /// </summary>
        internal static string MSG4093 {
            get {
                return ResourceManager.GetString("MSG4093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search installation slip for receive returned equipment not found.
        /// </summary>
        internal static string MSG4094 {
            get {
                return ResourceManager.GetString("MSG4094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Inventory slip for receive returned equipment not found.
        /// </summary>
        internal static string MSG4095 {
            get {
                return ResourceManager.GetString("MSG4095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to confirm receive returned equipment?.
        /// </summary>
        internal static string MSG4096 {
            get {
                return ResourceManager.GetString("MSG4096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack was used to receive returned equipment already..
        /// </summary>
        internal static string MSG4097 {
            get {
                return ResourceManager.GetString("MSG4097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account has no permission to do this action..
        /// </summary>
        internal static string MSG4098 {
            get {
                return ResourceManager.GetString("MSG4098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect data type.
        /// </summary>
        internal static string MSG4099 {
            get {
                return ResourceManager.GetString("MSG4099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix stock adjustment will be confirmed. Do you want to continous?.
        /// </summary>
        internal static string MSG4100 {
            get {
                return ResourceManager.GetString("MSG4100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment stock qty must more than or equal to Fixed stock adjustment qty..
        /// </summary>
        internal static string MSG4101 {
            get {
                return ResourceManager.GetString("MSG4101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Adjustment qty must be less than stock qty before adjustment.
        /// </summary>
        internal static string MSG4102 {
            get {
                return ResourceManager.GetString("MSG4102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction date must be in current month.
        /// </summary>
        internal static string MSG4103 {
            get {
                return ResourceManager.GetString("MSG4103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no.,{0}, is not Normal rack..
        /// </summary>
        internal static string MSG4104 {
            get {
                return ResourceManager.GetString("MSG4104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of specified destination rack no. {0}/destination area/equipment does not match with the combination of such rack no. {0}/area/equipment registered on rack master..
        /// </summary>
        internal static string MSG4105 {
            get {
                return ResourceManager.GetString("MSG4105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For rack no. ,{0}, there is rack no. ,{1}, which reference on this equipment code and area already..
        /// </summary>
        internal static string MSG4106 {
            get {
                return ResourceManager.GetString("MSG4106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment code , {0}, In case input &quot;Destination rack no.&quot; same as &quot;Source rack no.&quot;, &quot;Transfer qty&quot; must be inputted equal to &quot;Stock qty&quot;..
        /// </summary>
        internal static string MSG4107 {
            get {
                return ResourceManager.GetString("MSG4107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For rack no. , {0}, In case Input &quot;Destination rack no.&quot; same as &quot;Source rack no.&quot;, equipment qty must be 0..
        /// </summary>
        internal static string MSG4108 {
            get {
                return ResourceManager.GetString("MSG4108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment, {0}, not exists in Inventory database..
        /// </summary>
        internal static string MSG4109 {
            get {
                return ResourceManager.GetString("MSG4109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input information into {0}..
        /// </summary>
        internal static string MSG4112 {
            get {
                return ResourceManager.GetString("MSG4112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to register special stock out?.
        /// </summary>
        internal static string MSG4113 {
            get {
                return ResourceManager.GetString("MSG4113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Vat and WHT must not be more than Total amount.
        /// </summary>
        internal static string MSG4114 {
            get {
                return ResourceManager.GetString("MSG4114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminate equipment will be confirm. Do you want to continue?.
        /// </summary>
        internal static string MSG4115 {
            get {
                return ResourceManager.GetString("MSG4115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System does not freezed current inventory data..
        /// </summary>
        internal static string MSG4116 {
            get {
                return ResourceManager.GetString("MSG4116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank checking slip is created already..
        /// </summary>
        internal static string MSG4117 {
            get {
                return ResourceManager.GetString("MSG4117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating blank checking slip is fail..
        /// </summary>
        internal static string MSG4118 {
            get {
                return ResourceManager.GetString("MSG4118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment code, {0}, please select [Equipment area]..
        /// </summary>
        internal static string MSG4119 {
            get {
                return ResourceManager.GetString("MSG4119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MSG4120 {
            get {
                return ResourceManager.GetString("MSG4120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, All child equipments which refer to same parent equipment must be input same stock-out quantity..
        /// </summary>
        internal static string MSG4121 {
            get {
                return ResourceManager.GetString("MSG4121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-out qty must input more than 0..
        /// </summary>
        internal static string MSG4122 {
            get {
                return ResourceManager.GetString("MSG4122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment {0}, must be type is General or Material only..
        /// </summary>
        internal static string MSG4123 {
            get {
                return ResourceManager.GetString("MSG4123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment {0}, has child equipment. Please purchase by child equipment..
        /// </summary>
        internal static string MSG4124 {
            get {
                return ResourceManager.GetString("MSG4124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Stock-In Date(From)] must be less than or equal to [Stock-In Date(To)]..
        /// </summary>
        internal static string MSG4125 {
            get {
                return ResourceManager.GetString("MSG4125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account has no permission retrieve this Slip..
        /// </summary>
        internal static string MSG4126 {
            get {
                return ResourceManager.GetString("MSG4126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not returned equipment quantity for receiving..
        /// </summary>
        internal static string MSG4127 {
            get {
                return ResourceManager.GetString("MSG4127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no., {0}, Equipment {1}, Cannot specify same Empty rack on [Destination rack no.] if [Source rack no.] has difference [Equipment code]..
        /// </summary>
        internal static string MSG4128 {
            get {
                return ResourceManager.GetString("MSG4128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get DepreciationPeriod for contract and revenue from tbt_RentalContractBasic.
        /// </summary>
        internal static string MSG4129 {
            get {
                return ResourceManager.GetString("MSG4129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belonged office of user is not permission for acess to this screen..
        /// </summary>
        internal static string MSG4130 {
            get {
                return ResourceManager.GetString("MSG4130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is mismatch in inventory qty of seconhand equipment. Please contact department which control inventory.
        /// </summary>
        internal static string MSG4131 {
            get {
                return ResourceManager.GetString("MSG4131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register because total amount exceed 10 digits..
        /// </summary>
        internal static string MSG4132 {
            get {
                return ResourceManager.GetString("MSG4132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not equipment data for register Purchase order..
        /// </summary>
        internal static string MSG4133 {
            get {
                return ResourceManager.GetString("MSG4133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record to edit &apos;Modify order qty&apos;..
        /// </summary>
        internal static string MSG4134 {
            get {
                return ResourceManager.GetString("MSG4134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, cannot stock-out because [New inst. sale] is more than project stocked out qty..
        /// </summary>
        internal static string MSG4135 {
            get {
                return ResourceManager.GetString("MSG4135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, cannot stock-out because [New inst. sample] is more than project stocked out qty..
        /// </summary>
        internal static string MSG4136 {
            get {
                return ResourceManager.GetString("MSG4136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, cannot stock-out because [New inst. rental] is more than project stocked out qty..
        /// </summary>
        internal static string MSG4137 {
            get {
                return ResourceManager.GetString("MSG4137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment code, {0}, cannot stock-out because [Secondhand inst. rental] is more than project stocked out qty..
        /// </summary>
        internal static string MSG4138 {
            get {
                return ResourceManager.GetString("MSG4138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transfer rack no. {0}, Equipment code, {1}, normal rack to normal rack which there are equipment qty &gt; 0..
        /// </summary>
        internal static string MSG4139 {
            get {
                return ResourceManager.GetString("MSG4139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment {0}, is logical delete already..
        /// </summary>
        internal static string MSG4140 {
            get {
                return ResourceManager.GetString("MSG4140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no. ,{0}, cannot stock-out because slip status is not &apos;Not stock-out&apos; or &apos;Partial stock-out&apos;..
        /// </summary>
        internal static string MSG4141 {
            get {
                return ResourceManager.GetString("MSG4141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack no. ,{0}, cannot stock-out because slip status is not &apos;Not stock-out&apos;..
        /// </summary>
        internal static string MSG4142 {
            get {
                return ResourceManager.GetString("MSG4142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment ,{0}, cannot modify equipment quantity because there is no inventory at buffer W/H and user W/H..
        /// </summary>
        internal static string MSG4143 {
            get {
                return ResourceManager.GetString("MSG4143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount must be less than Total amount.
        /// </summary>
        internal static string MSG4144 {
            get {
                return ResourceManager.GetString("MSG4144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify unit..
        /// </summary>
        internal static string MSG4145 {
            get {
                return ResourceManager.GetString("MSG4145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-in slip no. already registered asset..
        /// </summary>
        internal static string MSG4146 {
            get {
                return ResourceManager.GetString("MSG4146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to input total price equals to 0? ({0}).
        /// </summary>
        internal static string MSG4147 {
            get {
                return ResourceManager.GetString("MSG4147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update or cancel stock-in slip after calculate monthly average price..
        /// </summary>
        internal static string MSG4148 {
            get {
                return ResourceManager.GetString("MSG4148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineup of {0} is &apos;Stop sale&apos;..
        /// </summary>
        internal static string MSG4149 {
            get {
                return ResourceManager.GetString("MSG4149", resourceCulture);
            }
        }
    }
}
