//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ISS090 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ISS090() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ISS090", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string btnRetrieve {
            get {
                return ResourceManager.GetString("btnRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation start date.
        /// </summary>
        internal static string haderInstallStartDate {
            get {
                return ResourceManager.GetString("haderInstallStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        internal static string headerDocumentName {
            get {
                return ResourceManager.GetString("headerDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Download&lt;/div&gt;.
        /// </summary>
        internal static string headerDownload {
            get {
                return ResourceManager.GetString("headerDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Edit&lt;/div&gt;.
        /// </summary>
        internal static string headerEdit {
            get {
                return ResourceManager.GetString("headerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify e-mail.
        /// </summary>
        internal static string headerEmailAddress {
            get {
                return ResourceManager.GetString("headerEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical check date.
        /// </summary>
        internal static string headerIEFirstCheckDate {
            get {
                return ResourceManager.GetString("headerIEFirstCheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical last inspection date.
        /// </summary>
        internal static string headerIELastInspectionDate {
            get {
                return ResourceManager.GetString("headerIELastInspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete date.
        /// </summary>
        internal static string headerInstallCompleteDate {
            get {
                return ResourceManager.GetString("headerInstallCompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last subcontractor fee.
        /// </summary>
        internal static string headerLastInstallFee {
            get {
                return ResourceManager.GetString("headerLastInstallFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of register installation request.
        /// </summary>
        internal static string HeaderRegisterNo {
            get {
                return ResourceManager.GetString("HeaderRegisterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string headerRemove {
            get {
                return ResourceManager.GetString("headerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;&quot;&gt;Remove&lt;/div&gt;.
        /// </summary>
        internal static string headerRemove1 {
            get {
                return ResourceManager.GetString("headerRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept inspect notice.
        /// </summary>
        internal static string lblAcceptInspectNotice {
            get {
                return ResourceManager.GetString("lblAcceptInspectNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual PO amount.
        /// </summary>
        internal static string lblActualPOAmount {
            get {
                return ResourceManager.GetString("lblActualPOAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string lblAdjustment {
            get {
                return ResourceManager.GetString("lblAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment contents.
        /// </summary>
        internal static string lblAdjustmentContents {
            get {
                return ResourceManager.GetString("lblAdjustmentContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance payment.
        /// </summary>
        internal static string lblAdvancePayment {
            get {
                return ResourceManager.GetString("lblAdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string lblApprove {
            get {
                return ResourceManager.GetString("lblApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve no. 1.
        /// </summary>
        internal static string lblApproveNo1 {
            get {
                return ResourceManager.GetString("lblApproveNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve no. 2.
        /// </summary>
        internal static string lblApproveNo2 {
            get {
                return ResourceManager.GetString("lblApproveNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve no. 3.
        /// </summary>
        internal static string lblApproveNo3 {
            get {
                return ResourceManager.GetString("lblApproveNo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached document list.
        /// </summary>
        internal static string lblAttachedDocList {
            get {
                return ResourceManager.GetString("lblAttachedDocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing installation fee.
        /// </summary>
        internal static string lblBIllingInstallFee {
            get {
                return ResourceManager.GetString("lblBIllingInstallFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change before operation information.
        /// </summary>
        internal static string lblChangeBeforeOperation {
            get {
                return ResourceManager.GetString("lblChangeBeforeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change reason.
        /// </summary>
        internal static string lblChangeReason {
            get {
                return ResourceManager.GetString("lblChangeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change requester.
        /// </summary>
        internal static string lblChangeRequester {
            get {
                return ResourceManager.GetString("lblChangeRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check charge technical.
        /// </summary>
        internal static string lblCheckChargeIE {
            get {
                return ResourceManager.GetString("lblCheckChargeIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complain.
        /// </summary>
        internal static string lblComplain {
            get {
                return ResourceManager.GetString("lblComplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract no..
        /// </summary>
        internal static string lblContractCode {
            get {
                return ResourceManager.GetString("lblContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract no./Project code.
        /// </summary>
        internal static string lblContractProjectCode {
            get {
                return ResourceManager.GetString("lblContractProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer building (English).
        /// </summary>
        internal static string lblContractPurchaserAddress {
            get {
                return ResourceManager.GetString("lblContractPurchaserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer building (Local).
        /// </summary>
        internal static string lblContractPurchaserAddressLocal {
            get {
                return ResourceManager.GetString("lblContractPurchaserAddressLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name (English).
        /// </summary>
        internal static string lblContractPurchaserName {
            get {
                return ResourceManager.GetString("lblContractPurchaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name (Local).
        /// </summary>
        internal static string lblContractPurchaserNameLocal {
            get {
                return ResourceManager.GetString("lblContractPurchaserNameLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost rate.
        /// </summary>
        internal static string lblCostRate {
            get {
                return ResourceManager.GetString("lblCostRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer PIC dept..
        /// </summary>
        internal static string lblCustomerStaffBelonging {
            get {
                return ResourceManager.GetString("lblCustomerStaffBelonging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer PIC.
        /// </summary>
        internal static string lblCustomerStaffName {
            get {
                return ResourceManager.GetString("lblCustomerStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer staff telephone no..
        /// </summary>
        internal static string lblCustomerStaffTelNo {
            get {
                return ResourceManager.GetString("lblCustomerStaffTelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (dd/MM/yyyy).
        /// </summary>
        internal static string lblDMY {
            get {
                return ResourceManager.GetString("lblDMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit installation management information.
        /// </summary>
        internal static string lblEditInformation {
            get {
                return ResourceManager.GetString("lblEditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation PO e-mail notice target.
        /// </summary>
        internal static string lblEmailAddress {
            get {
                return ResourceManager.GetString("lblEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected installation finish date.
        /// </summary>
        internal static string lblExpectInstallationCompleteDate {
            get {
                return ResourceManager.GetString("lblExpectInstallationCompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected installation start date.
        /// </summary>
        internal static string lblExpectInstallationStartDate {
            get {
                return ResourceManager.GetString("lblExpectInstallationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected installation complete date.
        /// </summary>
        internal static string lblExpectInstallCompleteDate {
            get {
                return ResourceManager.GetString("lblExpectInstallCompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected installation start date.
        /// </summary>
        internal static string lblExpectInstallStartDate {
            get {
                return ResourceManager.GetString("lblExpectInstallStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation PO information.
        /// </summary>
        internal static string lblHeaderInstallPO {
            get {
                return ResourceManager.GetString("lblHeaderInstallPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation information (in case of contract).
        /// </summary>
        internal static string lblHeaderName {
            get {
                return ResourceManager.GetString("lblHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation information (in case of project).
        /// </summary>
        internal static string lblHeaderName2 {
            get {
                return ResourceManager.GetString("lblHeaderName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation request information.
        /// </summary>
        internal static string lblHeaderName3 {
            get {
                return ResourceManager.GetString("lblHeaderName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register installation PO information.
        /// </summary>
        internal static string lblHeaderPO {
            get {
                return ResourceManager.GetString("lblHeaderPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified code.
        /// </summary>
        internal static string lblHeaderSpecified {
            get {
                return ResourceManager.GetString("lblHeaderSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div align=&apos;left&apos;&gt;(1) Technical check date&lt;br /&gt;(2) Technical last inspection date&lt;/div&gt;.
        /// </summary>
        internal static string lblIEDateDisplay {
            get {
                return ResourceManager.GetString("lblIEDateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical evaluation.
        /// </summary>
        internal static string lblIEEvaluation {
            get {
                return ResourceManager.GetString("lblIEEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical check date.
        /// </summary>
        internal static string lblIEFirstCheckDate {
            get {
                return ResourceManager.GetString("lblIEFirstCheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical last inspection date.
        /// </summary>
        internal static string lblIELastInspectionDate {
            get {
                return ResourceManager.GetString("lblIELastInspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical man power.
        /// </summary>
        internal static string lblIEManPower {
            get {
                return ResourceManager.GetString("lblIEManPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical staff 1.
        /// </summary>
        internal static string lblIEStaff1 {
            get {
                return ResourceManager.GetString("lblIEStaff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical staff 2.
        /// </summary>
        internal static string lblIEStaff2 {
            get {
                return ResourceManager.GetString("lblIEStaff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct IM charges.
        /// </summary>
        internal static string lblIMFee {
            get {
                return ResourceManager.GetString("lblIMFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete date.
        /// </summary>
        internal static string lblInstallationCompleteDate {
            get {
                return ResourceManager.GetString("lblInstallationCompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation PO e-mail notice target.
        /// </summary>
        internal static string lblInstallationEmail {
            get {
                return ResourceManager.GetString("lblInstallationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcontractor Fee 1.
        /// </summary>
        internal static string lblInstallationFee1 {
            get {
                return ResourceManager.GetString("lblInstallationFee1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcontractor Fee 2.
        /// </summary>
        internal static string lblInstallationFee2 {
            get {
                return ResourceManager.GetString("lblInstallationFee2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcontractor Fee 3.
        /// </summary>
        internal static string lblInstallationFee3 {
            get {
                return ResourceManager.GetString("lblInstallationFee3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation no..
        /// </summary>
        internal static string lblInstallationMANo {
            get {
                return ResourceManager.GetString("lblInstallationMANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation memo.
        /// </summary>
        internal static string lblInstallationMemo {
            get {
                return ResourceManager.GetString("lblInstallationMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation start date.
        /// </summary>
        internal static string lblInstallationStartDate {
            get {
                return ResourceManager.GetString("lblInstallationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation type.
        /// </summary>
        internal static string lblInstallationType {
            get {
                return ResourceManager.GetString("lblInstallationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div align=&apos;left&apos;&gt;(1) Installation start date&lt;br /&gt;(2) Installation complete date&lt;/div&gt;.
        /// </summary>
        internal static string lblInstallDateDisplay {
            get {
                return ResourceManager.GetString("lblInstallDateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation memo history.
        /// </summary>
        internal static string lblInstallMemoHistory {
            get {
                return ResourceManager.GetString("lblInstallMemoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last subcontractor fee.
        /// </summary>
        internal static string lblLastInstallationFee {
            get {
                return ResourceManager.GetString("lblLastInstallationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last paid date.
        /// </summary>
        internal static string lblLastPaidDate {
            get {
                return ResourceManager.GetString("lblLastPaidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man power (person).
        /// </summary>
        internal static string lblManpower {
            get {
                return ResourceManager.GetString("lblManpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Deduct charges.
        /// </summary>
        internal static string lblMaterialFee {
            get {
                return ResourceManager.GetString("lblMaterialFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New building mgmt. cost.
        /// </summary>
        internal static string lblNewBuildingMgmtCost {
            get {
                return ResourceManager.GetString("lblNewBuildingMgmtCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New building mgmt. type.
        /// </summary>
        internal static string lblNewBuildingMgmtType {
            get {
                return ResourceManager.GetString("lblNewBuildingMgmtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New connection telephone no..
        /// </summary>
        internal static string lblNewConnectTelNo {
            get {
                return ResourceManager.GetString("lblNewConnectTelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New building/Old building.
        /// </summary>
        internal static string lblNewOldBuilding {
            get {
                return ResourceManager.GetString("lblNewOldBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New telephone line open date.
        /// </summary>
        internal static string lblNewTelLineOpenDate {
            get {
                return ResourceManager.GetString("lblNewTelLineOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New telephone line owner.
        /// </summary>
        internal static string lblNewTelLineOwner {
            get {
                return ResourceManager.GetString("lblNewTelLineOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No check.
        /// </summary>
        internal static string lblNoCheck {
            get {
                return ResourceManager.GetString("lblNoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal installation fee.
        /// </summary>
        internal static string lblNormalInstallFee {
            get {
                return ResourceManager.GetString("lblNormalInstallFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal subcontractor PO amount.
        /// </summary>
        internal static string lblNormalSubContractorPOAmount {
            get {
                return ResourceManager.GetString("lblNormalSubContractorPOAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation office.
        /// </summary>
        internal static string lblOperationOffice {
            get {
                return ResourceManager.GetString("lblOperationOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string lblOther {
            get {
                return ResourceManager.GetString("lblOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct other charges.
        /// </summary>
        internal static string lblOtherFee {
            get {
                return ResourceManager.GetString("lblOtherFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string lblPaid {
            get {
                return ResourceManager.GetString("lblPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid date 1.
        /// </summary>
        internal static string lblPaidDate1 {
            get {
                return ResourceManager.GetString("lblPaidDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid date 2.
        /// </summary>
        internal static string lblPaidDate2 {
            get {
                return ResourceManager.GetString("lblPaidDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid date 3.
        /// </summary>
        internal static string lblPaidDate3 {
            get {
                return ResourceManager.GetString("lblPaidDate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning no..
        /// </summary>
        internal static string lblPlanCode {
            get {
                return ResourceManager.GetString("lblPlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update.
        /// </summary>
        internal static string lblPOAdd {
            get {
                return ResourceManager.GetString("lblPOAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string lblPOClear {
            get {
                return ResourceManager.GetString("lblPOClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO no..
        /// </summary>
        internal static string lblPONo {
            get {
                return ResourceManager.GetString("lblPONo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string lblProductName {
            get {
                return ResourceManager.GetString("lblProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit amount.
        /// </summary>
        internal static string lblProfitAmount {
            get {
                return ResourceManager.GetString("lblProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project representative address.
        /// </summary>
        internal static string lblProjectAddress {
            get {
                return ResourceManager.GetString("lblProjectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project code.
        /// </summary>
        internal static string lblProjectCode {
            get {
                return ResourceManager.GetString("lblProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string lblProjectName {
            get {
                return ResourceManager.GetString("lblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project customer name (English).
        /// </summary>
        internal static string lblProjectPurchaserName {
            get {
                return ResourceManager.GetString("lblProjectPurchaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project customer name (Local).
        /// </summary>
        internal static string lblProjectPurchaserNameLocal {
            get {
                return ResourceManager.GetString("lblProjectPurchaserNameLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project representative address.
        /// </summary>
        internal static string lblProjectrepresentAddress {
            get {
                return ResourceManager.GetString("lblProjectrepresentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed installation complete date.
        /// </summary>
        internal static string lblProposedInstallationCompleteDate {
            get {
                return ResourceManager.GetString("lblProposedInstallationCompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed installation start date.
        /// </summary>
        internal static string lblProposedInstallationStartDate {
            get {
                return ResourceManager.GetString("lblProposedInstallationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register installation management information.
        /// </summary>
        internal static string lblRegisterHeader {
            get {
                return ResourceManager.GetString("lblRegisterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string lblReject {
            get {
                return ResourceManager.GetString("lblReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark IM.
        /// </summary>
        internal static string lblRemarkIM {
            get {
                return ResourceManager.GetString("lblRemarkIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request approve.
        /// </summary>
        internal static string lblRequestApprove {
            get {
                return ResourceManager.GetString("lblRequestApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request approve installation e-mail.
        /// </summary>
        internal static string lblRequestApproveInstall {
            get {
                return ResourceManager.GetString("lblRequestApproveInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman 1.
        /// </summary>
        internal static string lblSalesMan1 {
            get {
                return ResourceManager.GetString("lblSalesMan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman 2.
        /// </summary>
        internal static string lblSalesMan2 {
            get {
                return ResourceManager.GetString("lblSalesMan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOM&apos;s payment.
        /// </summary>
        internal static string lblSecomPayment {
            get {
                return ResourceManager.GetString("lblSecomPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security type code.
        /// </summary>
        internal static string lblSecurityTypeCode {
            get {
                return ResourceManager.GetString("lblSecurityTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s building (English).
        /// </summary>
        internal static string lblSiteAddress {
            get {
                return ResourceManager.GetString("lblSiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s building (Local).
        /// </summary>
        internal static string lblSiteAddressLocal {
            get {
                return ResourceManager.GetString("lblSiteAddressLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s name (English).
        /// </summary>
        internal static string lblSiteName {
            get {
                return ResourceManager.GetString("lblSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premise&apos;s name (Local).
        /// </summary>
        internal static string lblSiteNameLocal {
            get {
                return ResourceManager.GetString("lblSiteNameLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub. group name.
        /// </summary>
        internal static string lblSubContractorGroupName {
            get {
                return ResourceManager.GetString("lblSubContractorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub. name.
        /// </summary>
        internal static string lblSubContractorName {
            get {
                return ResourceManager.GetString("lblSubContractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register subcontractor information.
        /// </summary>
        internal static string lblSubHeaderPO {
            get {
                return ResourceManager.GetString("lblSubHeaderPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THB.
        /// </summary>
        internal static string lblTHB {
            get {
                return ResourceManager.GetString("lblTHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of last subcontractor fee.
        /// </summary>
        internal static string lblTotalLastInstallFee {
            get {
                return ResourceManager.GetString("lblTotalLastInstallFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User code.
        /// </summary>
        internal static string lblUserCode {
            get {
                return ResourceManager.GetString("lblUserCode", resourceCulture);
            }
        }
    }
}
